### ISSUE TITLE
Upgrade kube-bench from v0.6.5 to v0.6.6

### ISSUE THREAD

**Issue by brandonw** [aquasecurity/starboard#1032]
The current base image of kube-bench v0.6.5 (alpine:3.14.2) has some busybox vulnerabilities that have been addressed with the latest version of kube-bench v0.6.6 (alpine:3.15.0).

**Comment by danielpacak** [comment]
Would you like to contribute by opening a PR to bump kube-bench up from v0.6.5 to v0.6.6 @brandonw ?

**Comment by brandonw** [comment]
Sure I would be happy to.

Has there been a change in updating the static manifests since https://github.com/brandonw/starboard/blob/main/CONTRIBUTING.md#update-static-yaml-manifests was last updated? It doesn't look as if `deploy/static/04-starboard-operator.deployment.yaml` exists, and the `namespace` appears to be removed when rendering the relevant templates.

**Comment by danielpacak** [comment]
Good catch @brandonw We should have updated the CONTRIBUTING.md with latest changes to static YAMLs. Starboard Deployment has been moved to ./deploy/static/05-starboard-operator.deployment.yaml and we introduced ./deploy/static/starboard.yaml that is generated with ./hack/update-starboard.yaml.sh

To upgrade kube-bench you can:
- [ ] Update image ref in deploy/helm/values.yaml
- [ ] Update image ref in deploy/static/03-starboard-operator.config.yaml
- [ ] Run ./hack/update-starboard.yaml.sh to update deploy/static/starboard.yaml

Hopefully it makes sense 🤓 

> TIP Relying on https://github.com/aquasecurity/starboard/blob/main/CONTRIBUTING.md#update-static-yaml-manifests without #216 being resolve may be tricky.

**Comment by danielpacak** [comment]
@brandonw Are you able to work on this item? We're about to release v0.15.0 and it would be nice to include it. Otherwise I can take it over or we push it for v0.16.0.

**Comment by brandonw** [comment]
Sorry @danielpacak, I was initially going to make a PR but then priorities shifted suddenly. I won't be able to handle this any time soon.
