### ISSUE TITLE
Please update krew plugin version to the latest

### ISSUE THREAD

**Issue by artemisok** [aquasecurity/starboard#1086]
**What steps did you take and what happened:**
1. kubectl krew install starboard

**What did you expect to happen:**
I expected it to be installed with the latest version which has arch=arm64 binary.
https://github.com/aquasecurity/starboard/releases/tag/v0.15.0-rc7
Krew still installs the previous version therefore I receive the error below.
**Anything else you would like to add:**
I received 
I0330 12:30:38.153977   14714 scanner.go:78] Reading plugin "starboard" from /Users/dok/.krew/index/default/plugins
I0330 12:30:38.154269   14714 install.go:148] Will install plugin: default/starboard
Installing plugin: starboard
I0330 12:30:38.154273   14714 install.go:59] Looking for installed versions
I0330 12:30:38.154283   14714 platform.go:43] Matching platform for labels(arch=arm64,os=darwin)
W0330 12:30:38.154304   14714 install.go:164] failed to install plugin "starboard": plugin "starboard" does not offer installation for this platform
F0330 12:30:38.154354   14714 root.go:78] plugin "starboard" does not offer installation for this platform

**Environment:**
 M1, 2020, macOS Big Sur Version 11.6.4

**Comment by danielpacak** [comment]
We are not publishing release candidates to krew index. We'll only published the actual release v0.15.0 quite soon.
