### ISSUE TITLE
feat: remove all category from CRDs

### ISSUE THREAD

**Issue by danielpacak** [aquasecurity/starboard#1090]
In general, it's not desirable to list Starboard resources with `kubectl get all` command. Therefore, we should remove the all category from all CRDs. See also #1080.

**Comment by nublarsec** [comment]
@danielpacak If I'm not mistaken I think you've already done this in Oct 2021: https://github.com/aquasecurity/starboard/commit/b2e65889830c3ea2dbde58a231418ed2722f52f6

I believe the user in #1080 was using v0.14.1 before this change was made. Hope that helps.

**Comment by danielpacak** [comment]
We've only done that for cluster-scoped CRDs but we want to do the same for namespaced CRDs, i.e. ConfigAuditReport, and VulnerabilityReport
