### ISSUE TITLE
TTL flag ignored

### ISSUE THREAD

**Issue by javixeneize** [aquasecurity/starboard#1158]
**What steps did you take and what happened:**

deployed starboard with

  helm install starboard-operator aqua/starboard-operator \
  --namespace starboard-system \
  --create-namespace \
  --set="trivy.ignoreUnfixed=true" \
   --set="operator.vulnerabilityScannerReportTTL=1m" \
  --version 0.10.4

**What did you expect to happen:**
Every minute, the existing trivy reports should be cleaned and a new scan should be triggered, according to https://github.com/aquasecurity/starboard/commit/ab3974f34d367bd5fc311e8832be289430650f25

Reports are not cleared and also no new scan is triggered 

Is there a minimum value for TTL? Should it be bigger than that?

Thanks

**Comment by danielpacak** [comment]
This flag is not ignored, but setting TTL to 1 minute, which is less than scan job duration, doesn't make much sense. You'll see scan jobs being created and vulnerability reports deleted constantly.

The TTL is supposed to be set in hours to rescan container image when we update Trivy vulnerability database.

**Comment by javixeneize** [comment]
thanks, i will set it to 1 hour
