### ISSUE TITLE
Migrate Starboard to Trivy Operator

### ISSUE THREAD

**Issue by chen-keinan** [aquasecurity/starboard#1167]
**What steps did you take and what happened:**

Migrating Starboard to Trivy-Operator

Associated issue:
- Replace starboard image #1166 
- create trivy-operator plugin in index krew #1164 
- naming refactor from Starboard to Trivy-operator #1162 
- Add starboard to operator hub #1165 
- remove starboard CLI #1168

**Comment by skuethe** [comment]
This is creating a lot of questions :)
Looking forward for some feedback in the discussions 🙏🏽
https://github.com/aquasecurity/starboard/discussions/1169

**Comment by chen-keinan** [comment]
@skuethe announcement #1173
