### ISSUE TITLE
Find vulnerability got stucked and get vulnerability return blank yaml

### ISSUE THREAD

**Issue by ipsita2192** [aquasecurity/starboard#130]
I am trying to find vulnerability and get vulnerability of deployment/nginx.
Getting below error:
bash-4.4# kubectl starboard --kubeconfig admin.conf init
bash-4.4# kubectl --kubeconfig admin.conf get deployment
NAME    READY   UP-TO-DATE   AVAILABLE   AGE
nginx   0/1     1            0           5d20h

bash-4.4#  kubectl starboard --kubeconfig admin.conf get vulnerabilities deployment/nginx --namespace default
error: exit status 1

bash-4.4#  kubectl starboard --kubeconfig admin.conf find vulnerabilities deploy/nginx -n default -v 3
I0825 06:11:09.435023   15858 scanner.go:56] Getting Pod template for workload: {Deployment nginx default}
I0825 06:11:09.458662   15858 scanner.go:71] Scanning with options: {ScanJobTimeout:0s DeleteScanJob:true}
I0825 06:11:09.459671   15858 runner.go:79] Running task and waiting forever
I0825 06:11:09.459876   15858 runnable_job.go:47] Creating runnable job: starboard/e4b32fa7-3a9a-4dae-a05c-f89e1aa32086
I0825 06:11:09.483017   15858 reflector.go:207] Starting reflector *v1.Job (30m0s) from pkg/mod/k8s.io/client-go@v0.19.0-alpha.3/toolscache/reflector.go:156
I0825 06:11:09.483064   15858 reflector.go:243] Listing and watching *v1.Job from pkg/mod/k8s.io/client-go@v0.19.0-alpha.3/tools/cachereflector.go:156

it got stucked in this page.

**Environment:**

- Starboard version (use `starboard version`): {Version:0.2.6 Commit:d43faefc56021ae55d4574054ce7de13175ca206 Date:2020-07-09T20:30:45Z}
- Kubernetes version (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.9", GitCommit:"2e808b7cb054ee242b68e62455323aa783991f03", GitTreeState:"clean", BuildDate:"2020-01-18T23:24:23Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc):
bash-4.4# cat /etc/alpine-release
3.9.6

**Comment by danielpacak** [comment]
Thank you for reporting this issue @ipsita2192 Would you be able to run Starboard with the `--delete-scan-job` flag set to false?
This might give us more insights into the scan Job that the we schedule behind the scenes:

```
kubectl starboard --kubeconfig admin.conf get vulnerabilities deployment/nginx \
  --namespace default \
  --delete-scan-job=false
```

With that could you share the description of the scan Job in the starboard namespace and logs for the corresponding Pod if it was scheduled.

**Comment by ipsita2192** [comment]
Tried with the above suggested way and getting error: "unknow flag : --delete-scan-job"

bash-4.4# kubectl starboard --kubeconfig admin.conf get vulnerabilities deployment/nginx --namespace default --delete-scan-job=false  error: unknown flag: --delete-scan-job
bash-4.4#

Then describe pods and getting ImagePullBackOff error.
bash-4.4# kubectl --kubeconfig admin.conf get pods
NAME                     READY   STATUS             RESTARTS   AGE
nginx-77776fdcdc-8z9sw   0/1     ImagePullBackOff   0          3d2h

**Comment by danielpacak** [comment]
Hey @ipsita2192 I double checked on my end and the `--delete-scan-job` flag is available in Starboard v0.2.6:

```
kubectl starboard version
Starboard Version: {Version:0.2.6 Commit:d43faefc56021ae55d4574054ce7de13175ca206 Date:2020-07-09T20:30:45Z}
```

```
kubectl starboard find vuln deploy/nginx -v 3 --delete-scan-job=false
I0826 09:36:32.726807    2321 scanner.go:56] Getting Pod template for workload: {Deployment nginx default}
I0826 09:36:32.738025    2321 scanner.go:71] Scanning with options: {ScanJobTimeout:0s DeleteScanJob:false}
I0826 09:36:32.738074    2321 runner.go:79] Running task and waiting forever
I0826 09:36:32.738095    2321 runnable_job.go:47] Creating runnable job: starboard/70791e45-8eb3-4a5c-a29e-981cd9fda090
I0826 09:36:32.745042    2321 reflector.go:207] Starting reflector *v1.Job (30m0s) from pkg/mod/k8s.io/client-go@v0.19.0-alpha.3/tools/cache/reflector.go:156
I0826 09:36:32.745061    2321 reflector.go:243] Listing and watching *v1.Job from pkg/mod/k8s.io/client-go@v0.19.0-alpha.3/tools/cache/reflector.go:156
I0826 09:36:43.485928    2321 runnable_job.go:70] Stopping runnable job on task completion with status: Complete
I0826 09:36:43.485945    2321 runner.go:83] Stopping runner on task completion with error: <nil>
I0826 09:36:43.485952    2321 scanner.go:95] Scan job completed: starboard/70791e45-8eb3-4a5c-a29e-981cd9fda090
I0826 09:36:43.487994    2321 scanner.go:262] Getting logs for nginx container in job: starboard/70791e45-8eb3-4a5c-a29e-981cd9fda090
I0826 09:36:43.740805    2321 scanner.go:85] Skipping scan job deletion: starboard/70791e45-8eb3-4a5c-a29e-981cd9fda090
```

It seems that image pull has failed in your environment. Could you describe the Pod nginx-77776fdcdc-8z9sw and see why it failed? The `find vulnerabilities` command runs Trivy which is also trying to pull an image to scan it for vulnerabilities. So we need to figure out why it failed. Also could you confirm which image are you using? Is it nginx:1.16?

**Comment by ipsita2192** [comment]
Docker was not installed there inside the container. I have created another container with docker installed and execute find Vulnerability, it is running and results is given below

bash-4.4#  kubectl starboard --kubeconfig admin.conf find vulnerabilities deployment/nginx --namespace default -v 3
I0826 10:59:34.773122     647 scanner.go:56] Getting Pod template for workload: {Deployment nginx default}
I0826 10:59:34.790279     647 scanner.go:71] Scanning with options: {ScanJobTimeout:0s DeleteScanJob:true}
I0826 10:59:34.790547     647 runner.go:79] Running task and waiting forever
I0826 10:59:34.790767     647 runnable_job.go:47] Creating runnable job: starboard/2b245ab8-d174-4ab6-8793-7a7cb7c1d7b7
I0826 10:59:34.804626     647 reflector.go:207] Starting reflector *v1.Job (30m0s) from pkg/mod/k8s.io/client-go@v0.19.0-alpha.3/tools/cache/reflector.go:156
I0826 10:59:34.804648     647 reflector.go:243] Listing and watching *v1.Job from pkg/mod/k8s.io/client-go@v0.19.0-alpha.3/tools/cache/reflector.go:156
I0826 11:00:20.585653     647 runnable_job.go:70] Stopping runnable job on task completion with status: Complete
I0826 11:00:20.585696     647 runner.go:83] Stopping runner on task completion with error: <nil>
I0826 11:00:20.585707     647 scanner.go:95] Scan job completed: starboard/2b245ab8-d174-4ab6-8793-7a7cb7c1d7b7
I0826 11:00:20.587705     647 scanner.go:262] Getting logs for nginx container in job: starboard/2b245ab8-d174-4ab6-8793-7a7cb7c1d7b7
I0826 11:00:20.764173     647 scanner.go:88] Deleting scan job: starboard/2b245ab8-d174-4ab6-8793-7a7cb7c1d7b7



 But while I am executing get vulnerability command it exits with status 1
bash-4.4#  kubectl starboard --kubeconfig admin.conf get vulnerabilities deployment/nginx --namespace default --output yaml
error: exit status 1

Below is the Deployment details:

bash-4.4# kubectl --kubeconfig admin.conf get deployment nginx
NAME    READY   UP-TO-DATE   AVAILABLE   AGE
nginx   1/1     1            1           14m


bash-4.4# kubectl --kubeconfig admin.conf describe deployment nginx
Name:                   nginx
Namespace:              default
CreationTimestamp:      Wed, 26 Aug 2020 10:51:22 +0000
Labels:                 app=nginx
Annotations:            deployment.kubernetes.io/revision: 1
Selector:               app=nginx
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:  app=nginx
  Containers:
   nginx:
    Image:        nginx:1.16
    Port:         <none>
    Host Port:    <none>
    Environment:  <none>
    Mounts:       <none>
  Volumes:        <none>
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
  Progressing    True    NewReplicaSetAvailable
OldReplicaSets:  <none>
NewReplicaSet:   nginx-7ff78f74b9 (1/1 replicas created)
Events:
  Type    Reason             Age   From                   Message
  ----    ------             ----  ----                   -------
  Normal  ScalingReplicaSet  15m   deployment-controller  Scaled up replica set nginx-7ff78f74b9 to 1

**Comment by ipsita2192** [comment]
Now I am able to get vulnerability using below command:
kubectl --kubeconfig admin.conf get vulns --selector starboard.resource.kind=Deployment,starboard.resource.name=nginx --namespace default --output yaml

**Comment by ipsita2192** [comment]
Thank you  @danielpacak .

**Comment by danielpacak** [comment]
@ipsita2192 I'm going to close this issue as you get the vulnerability report for you deployment.

However, I opened another issue to follow up on bug in the `get vulnerabilities` subcommand, see #142
