### ISSUE TITLE
Write an integration test case for Polaris command

### ISSUE THREAD

**Issue by danielpacak** [aquasecurity/starboard#140]
To catch regressions we should have an integration test that runs starboard polaris command and asserts on `configauditreports` created.

**Comment by krisctl** [comment]
I'd happy to take a jab at this. Thanks

**Comment by danielpacak** [comment]
> I'd happy to take a jab at this. Thanks

I've actually created this issue to assign it to @krol3

**Comment by krol3** [comment]
Thanks @danielpacak

**Comment by danielpacak** [comment]
Resolved by: #146
