### ISSUE TITLE
Aqua logo looks wrong in HTML report

### ISSUE THREAD

**Issue by lizrice** [aquasecurity/starboard#156]
`k starboard get report deployment/nginx > out.html`
`open out.html`

The logo is stretched up-and-down. (We should update to the new Aqua logo anyway)

![Screenshot 2020-09-21 at 12 30 39](https://user-images.githubusercontent.com/458616/93761895-7ddf2200-fc06-11ea-8af5-1da68fd804e1.png)

- Starboard version (use `starboard version`): 0.4.0
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): Mac / safari browser

**Comment by krabhisharma** [comment]
Can I solve.. This @lizrice

**Comment by danielpacak** [comment]
> Can I solve.. This @lizrice

👋 @krabhisharma Thank you for interesting in resolving this issue. However, I'd better leave it with @danielsagi as we'd like to update the logo to the one that's currently used by rebranded Aqua
