### ISSUE TITLE
Hacktoberfest at Aqua Security

### ISSUE THREAD

**Issue by danielpacak** [aquasecurity/starboard#162]
Dear community, we appreciate you and your contribution to the success of our open source projects! In celebration of [Hacktoberfest](https://hacktoberfest.digitalocean.com/), we would like to extend our appreciation and reward your hard work. This repository is participating in Aqua Security 2020 Hacktoberfest campaign. For full details and guidelines please visit the official repo: [Hacktoberfest at Aqua Security](https://github.com/aquasecurity/Hacktoberfest).

**Comment by sanjana1604** [comment]
@danielpacak Thank you for the opportunity but  why this is mentioned under an issue??

**Comment by danielpacak** [comment]
It's over. Many thanks for everyone who participated and congratulations to the winners. See you next year!
