### ISSUE TITLE
Add 'starboard config' command to read config values

### ISSUE THREAD

**Issue by danielpacak** [aquasecurity/starboard#166]
On init we create the `starboard` ConfigMap in the `starboard` namespace. The config map contains configuration params for scanners. Currently the only way to list the params is view or edit the ConfigMap. We'd like to have a dedicated command to hide the implementation details, wich may have the following interface:

```
$ starboard config --list
trivy.severity=UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
trivy.httpProxy=http://someproxy:8080
polaris.config.yaml=...
```

```
$ starboard config --list --name-only
trivy.severity
trivy.httpProxy
polaris.config.yaml
```

```
$ starboard config --get trivy.severity
UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
```

The interface is inspired by git config command. However the tricky part might be to display long multi-line config values such as `polaris.config.yaml`. Designing the CLI is part of this task and preliminary step before you start coding.

**Comment by avats-dev** [comment]
hey @danielpacak , I want to work on this. Can you guide me a bit how to resolve this? Thanks.

**Comment by sam-robson** [comment]
hi @danielpacak, after getting familiar with the repo over the past few days I'd quite like to pick this up (if you wouldn't mind @avats-dev - I saw you are also interested in issue 165). I'll send over my thoughts about the CLI design and how to handle the multi-line values asap.

**Comment by avats-dev** [comment]
Ok @sam-robson no problem :+1: .

**Comment by sam-robson** [comment]
My thoughts about the CLI:
- Is a `--list` flag necessary, if the purpose of `starboard config` is to list the configuration parameters, by default? I think this might be preferable to requiring an additional flag, be it `--list` or `--get`, but that is just my instinctive 2c; I am new to CLI design.
- We should prioritize the `get` command, so that in the case where both `name-only` and `get` commands are invoked, we ignore the former.
- We should handle the multi-line config values as `kubectl describe configmaps --namespace=x` does, as follows:
```
$ starboard config
polaris.config.yaml:
----
checks:
  # reliability
  multipleReplicasForDeployment: ignore
  priorityClassNotSet: ignore
  ...
```

**Comment by danielpacak** [comment]
> My thoughts about the CLI:
> 
> * Is a `--list` flag necessary, if the purpose of `starboard config` is to list the configuration parameters, by default? I think this might be preferable to requiring an additional flag, be it `--list` or `--get`, but that is just my instinctive 2c; I am new to CLI design.
> * We should prioritize the `get` command, so that in the case where both `name-only` and `get` commands are invoked, we ignore the former.
> * We should handle the multi-line config values as `kubectl describe configmaps --namespace=x` does, as follows:
> 
> ```
> $ starboard config
> polaris.config.yaml:
> ----
> checks:
>   # reliability
>   multipleReplicasForDeployment: ignore
>   priorityClassNotSet: ignore
>   ...
> ```

👋 @sam-robson I'm happy to assign this one to you. Regarding your thoughts, I do agree with all of them and I'm okey with changing my original proposal, which was inspired by `git config` command. On the other hand, we should be consistent and compliant with kubectl as Starboard can be installed with krew plugins manager.

**Comment by avats-dev** [comment]
@danielpacak you can assign this one to @sam-robson , I've got enough on my plate for now. Thanks. :rocket:
