### ISSUE TITLE
Test Starboard on Azure Kubernetes Service (AKS)

### ISSUE THREAD

**Issue by danielpacak** [aquasecurity/starboard#175]
Configure Starboard CLI with a managed Kubernetes cluster on Microsoft Azure and walk through the Getting Started steps. Note any issues and problems that you might have.

**Comment by borkod** [comment]
I worked through the Getting Started section with a simple 3 node AKS cluster. No issues. Let me know if you want to validate the outputs of the vulnerabilities and config audits. I saved the outputs of all the commands and can provide them if you wish.

My one suggestion would be to have a step to create the dev namespace in the instructions. I already created an update to the README for this. #192 

Let me know if there are any other AKS tests that would be helpful. I'd be happy to assist.

**Comment by danielpacak** [comment]
> I worked through the Getting Started section with a simple 3 node AKS cluster. No issues. Let me know if you want to validate the outputs of the vulnerabilities and config audits. I saved the outputs of all the commands and can provide them if you wish.
> 
> My one suggestion would be to have a step to create the dev namespace in the instructions. I already created an update to the README for this. #192
> 
> Let me know if there are any other AKS tests that would be helpful. I'd be happy to assist.

👋 @borkod This is great news! Before we close this issue could you comment below with checklist of all steps that you performed? I'm wondering if you run also kube-bench and kube-hunter on your test cluster?

**Comment by borkod** [comment]
Hi. 
I provisioned a 3 node AKS cluster. I downloaded the starboard CLI (windows release). Then followed the instructions as specified in the Getting Started section:

1. `starboard init`
2. Verified deployed resources using `kubectl api-resources --api-group aquasecurity.github.io`
3. Created dev namespace using `kubectl create namespace dev`
4. `kubectl create deployment nginx --image nginx:1.16 --namespace dev`
5. `starboard find vulnerabilities deployment/nginx --namespace dev`
6. `starboard get vulnerabilities deployment/nginx --namespace dev --output yaml` (I also ran this command with output saved to a file)
7. `kubectl get vulnerabilityreport --selector starboard.resource.kind=Deployment,starboard.resource.name=nginx --namespace dev --output yaml` (Also ran the command saving the output to a file)
8. `starboard polaris deployment/nginx --namespace dev`
9. `starboard get configaudit deployment/nginx --namespace dev --output yaml` (Also saved output to a file)
10. `kubectl get configauditreport --selector starboard.resource.kind=Deployment,starboard.resource.name=nginx --namespace dev --output yaml` (Also saved output to a file)
11. Deleted my AKS cluster.

I did not run kube-bench or kube-hunter. I somehow missed those when reading through it first time. I'll run those later tonight and report back.

**Comment by danielpacak** [comment]
Thanks for all work @borkod This is very insightful. For kube-hunter I observed a similar behaviour even on a local KIND cluster, where a scan job hangs without any meaningful logs (see #126 ) Anyway the good news is that Trivy, Polaris, and kube-bench works. Let's close this one follow up in #126 to see why kube-hunter fails.
