### ISSUE TITLE
Test Starboard on Amazon EKS

### ISSUE THREAD

**Issue by danielpacak** [aquasecurity/starboard#176]
Configure Starboard CLI with an Amazon EKS and walk through the Getting Started steps. Note any issues and problems that you might have.

**Comment by sam-robson** [comment]
Hey @danielpacak, I'd quite like to take a look at this. Shall I note what I find in this thread?

**Comment by borkod** [comment]
Hi. I tested the Getting Started steps on an Amazon EKS cluster (using EC2 node pool). No issues.

**Comment by danielpacak** [comment]
@sam-robson I think we can note down the validation steps in in this thread and create follow up issues if we found some issues. And it would be great to see some evidence that you've actually run those tests such as logs dump or screencast if you will.

**Comment by danielpacak** [comment]
@borkod Would you provide more details about your EKS cluster and logs dump?

**Comment by borkod** [comment]
Hi.
I don't have the cluster any longer. I just provisioned an EKS cluster to test the Getting started steps and then destroyed it. IIRC there wasn't anything special about it. EKS cluster with 3 EC2 instances for node pool.

I don't think I ran kube-bench or kube-hunter. 

The only output I have are the audit report and vulnerability report:
[eks-reports.zip](https://github.com/aquasecurity/starboard/files/5449067/eks-reports.zip)

I can repeat the the test to see if there are any issues with kube-bench and kube-hunter (similar to issues I saw on AKS). Let me know if there are any specific logs I can provide once I repeat the test (e.g. kube-hunter job logs ?)

**Comment by krol3** [comment]
I had a cluster in EKS, and AKS I could tested it and validate too

**Comment by krol3** [comment]
Hi @danielpacak 

I tested in EKS, no issues. This is the details and steps:

k8s version: v1.17.9-eks-a84824
Starboard Version: {Version:0.6.0 Commit:ad6b9b99931d7524806f79b1329fdda82c75a715 Date:2020-10-14T20:14:11Z}

- starboard sample deployment nginx
- starboard kube-bench
- starboard kube-hunter
- starboard polaris
- starboard config

**Comment by danielpacak** [comment]
Thank you @borkod and @krol3 for testing. I assume that there're no major issues when using Starboard with Amazon EKS and will proceed with closing this issue.
