### ISSUE TITLE
Include links for tool-specific policy details 

### ISSUE THREAD

**Issue by danielpacak** [aquasecurity/starboard#18]
As a user, I might use Starboard tools to learn whether workloads are compliant or not compliant with policies. Those policies are enforced by third-party tools. Starboard CRDs could include a field for a link for discovering further details that can be populated by the third-party tool (or an adapter for it). For example, if an image doesn't meet an Aqua image policy, the vulnerability CRD for that image could link to the Aqua UI screen where that policy is configured.

**Comment by krol3** [comment]
Hi @danielpacak, will be add a field "external_link" in the CRD?, other tools like OPA do we have integration with starboard?
