### ISSUE TITLE
[cli] Allow configuring custom Docker image for each scanner

### ISSUE THREAD

**Issue by danielpacak** [aquasecurity/starboard#181]

**Comment by khushijindal** [comment]
Hey, @danielpacak Can you please elaborate on what needs to be done. I'll want to work on this.

**Comment by danielpacak** [comment]
👋 @khushijindal On init we do create the starboard ConfigMap in the starboard namespace. The ConfigMap contains configuration keys for the default images used by Trivy (`trivy.imageRef`) and kube-bench (`kube-bench.imageRef`).

This means that you can configure image references for Trivy and kube-bench without recompiling Starboard CLI.

For Polaris and kube-hunter scanners the images are hardcoded as Go string literals, but we'd like to configure them as well.

**Comment by danielpacak** [comment]
It's already done on the main branch. As documented in https://aquasecurity.github.io/starboard/configuration/, for each integrated scanner you can override its image reference:

- polaris.imageRef
- trivy.imageRef
- kube-bench.imageRef
- kube-hunter.imageRef
- aqua.imageRef
