### ISSUE TITLE
[operator] Integrate Polaris scanner

### ISSUE THREAD

**Issue by danielpacak** [aquasecurity/starboard#185]
In the same way we reconcile VulnerabilityReports we should reconcile ConfigAuditReports reports generated by Polaris scanner.

**Comment by krol3** [comment]
Hi @danielpacak , do you mean add Polaris in the starboard-operator? I found this related code, Will be?
- /cmd/starboard-operator/main.go
- pkg/operator/controller/reconciler.go

**Comment by danielpacak** [comment]
> Hi @danielpacak , do you mean add Polaris in the starboard-operator? I found this related code, Will be?
> 
> * /cmd/starboard-operator/main.go
> * pkg/operator/controller/reconciler.go

Yes. Currently we only reconcile VulnerabilityReports, but eventually we'd like to reconcile also ConfigAuditReports. This will involve changes in few other places, not only the files you mentioned.
