### ISSUE TITLE
Namespaced CRDs

### ISSUE THREAD

**Issue by danielpacak** [aquasecurity/starboard#19]
As a developer I may have access to only one k8s namespace for my project. I should be able to query security CRDs related to that namespace.

As an admin I have access to multiple k8s namespaces. I should be able to query security CRDs across all of them.

**Comment by krol3** [comment]
Hi @danielpacak, is this issue related with RBAC https://github.com/aquasecurity/starboard/issues/23

**Comment by danielpacak** [comment]
> Hi @danielpacak, is this issue related with RBAC #23

Yes. I think this was one of the very first requirements captured for Starboard to manage access to security resources

**Comment by lizrice** [comment]
it's working this way already
