### ISSUE TITLE
[operator] Scaffold an integration test for the operator

### ISSUE THREAD

**Issue by danielpacak** [aquasecurity/starboard#203]
We can test the operator as explained in https://book.kubebuilder.io/cronjob-tutorial/writing-tests.html

**Comment by krol3** [comment]
Nice!! If it's available, I'd like to try

**Comment by danielpacak** [comment]
> Nice!! If it's available, I'd like to try

Hey @krol3 I've got already PR for this one. For some reason it was not linked to this issue, but I fixed it
