### ISSUE TITLE
[cli] Use deterministic names for VulnerabilityReports

### ISSUE THREAD

**Issue by danielpacak** [aquasecurity/starboard#223]
**What steps did you take and what happened:**

```
kubectl starboard find vuln deploy/wordpress
kubectl get vuln -l starboard.resource.kind=Deployment -o wide
NAME                                   REPOSITORY          TAG   SCANNER   AGE   CRITICAL   HIGH   MEDIUM   LOW   UNKNOWN
0e4e1638-8133-4be6-8b87-dd6a7415a070   library/wordpress   4.9   Trivy     35s   91         294    290      417   2
```

**What did you expect to happen:**

```
kubectl get vuln -l starboard.resource.kind=Deployment -o wide
NAME                                   REPOSITORY          TAG   SCANNER   AGE   CRITICAL   HIGH   MEDIUM   LOW   UNKNOWN
deployment-wordpress-wordpress         library/wordpress   4.9   Trivy     35s   91         294    290      417   2
```

The name of a Vulnerability report should follow the patter: `<kind>-<resource name>-<container name>`

**Anything else you would like to add:**

We have deterministic names implemented for the operator and we want to be consistent.

**Environment:**

- Starboard version (use `starboard version`): 0.6.0
- Kubernetes version (use `kubectl version`): Any
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): Any

**Comment by krisctl** [comment]
hi @danielpacak,

Happy to help if you are still looking for someone to take a look.

Thanks!

**Comment by danielpacak** [comment]
> hi @danielpacak,
> 
> Happy to help if you are still looking for someone to take a look.
> 
> Thanks!

Thanks @krisctl I took this one already.
