### ISSUE TITLE
Implement the `rbac` subcommand

### ISSUE THREAD

**Issue by danielpacak** [aquasecurity/starboard#23]
Starboard is Kubernetes-native security application which stores vulnerability reports as custom security resources. To create such resources and risk scanners certain RBAC permissions are required.

Instead of listing all required roles in README  or YAML, I thought that we may provide the command, which is supposed to be run by cluster admins, to grant permission to a given subject:

```
kubectl starborad rbac \
  --user=dave \
  --user=loper \
  --group=terra-nowa \
   -n my-namespace | kubectl apply -f -
```

**Comment by krol3** [comment]
I'd like to help, I see the other open issue related to use starboard with gitops.

**Comment by danielpacak** [comment]
The init command is taking care of creating necessary RBAC objects to use Starboard CLI. In this approach we assume that the user in the current K8s context already has required permissions. Therefore, the rbac command would not be necessary.
