### ISSUE TITLE
starboard kube-hunter error: unknown flag: --interface

### ISSUE THREAD

**Issue by n3rd253** [aquasecurity/starboard#239]
**What steps did you take and what happened:**

Tried to run `kube-hunter --interface`

**What did you expect to happen:**
It scanned the network interfaces

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Starboard version (use `starboard version`): latest
- Kubernetes version (use `kubectl version`): 1.19
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc):

Ran as specified here

> Interface scanning
To specify interface scanning, you can use the --interface option (this will scan all of the machine's network interfaces). Example: kube-hunter --interface

Received

error: unknown flag: --interface
##[error]Bash exited with code '1'.

**Comment by danielsagi** [comment]
Hi @n3rd253 !
The `--interface` is intended for running kube-hunter manually on a host/container.
You might be confusing kube-hunter's original project and it's usage here on starboard.
When running with starboard, we backstage deploy kube-hunter with a `--pod` mode. it is hardcoded and meant to run this way. 

Also a side note, `--pod` internally speaking is basically `--interface` mode on steroids.
