### ISSUE TITLE
typo in docker details - and all through project

### ISSUE THREAD

**Issue by justisestell** [aquasecurity/starboard#242]
**What steps did you take and what happened:**

[Typos in the readme](https://github.com/aquasecurity/starboard/blob/master/README.md#docker) make the project confusing for first time users. 

I copied and paste the values listed in [the docker readme section](https://github.com/aquasecurity/starboard/blob/master/README.md#docker) and then realized, after trying a couple times, that the image name had a typo in it. 

Even the [bug report](https://github.com/aquasecurity/starboard/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) has a typo with Bracket vs Parentheses, see below.

[A clear and concise description of what the bug is, and what commands you ran.)

**What did you expect to happen:**

I expect the documentation to have basic linting and validation as the project continues to expand. 

**Anything else you would like to add:**

I hate raising an issue for this and appreciate the hard work of the team so far. I'd make a PR for the typos but, there seem to be a fair amount and think that this may be an actual ISSUE with the project. 

**Environment:**

- Starboard version (use `starboard version`):
- Kubernetes version (use `kubectl version`):
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc):

**Comment by danielpacak** [comment]
Thanks for the feedback @justisestell and I'm sorry to hear that you had problems pulling the image. I fixed the typos you pointed out so we do not confuse other folks.

Regarding the project ISSUE you could start a [discussion](https://github.com/aquasecurity/starboard/discussions) thread to make it better. In particular propose a way to review the docs or add some automated linter.
