### ISSUE TITLE
Jobs try to run on Windows

### ISSUE THREAD

**Issue by sylus** [aquasecurity/starboard#244]
**What steps did you take and what happened:**

I am running a cronjob which calls starboard with -v3 kube-bench but notice that some jobs are unable to run as they are trying to execute on windows nodes.

P.S. Thanks for the amazing tool :D 

**What did you expect to happen:**

The windows nodes are tainted.

**Anything else you would like to add:**

N/A

**Environment:**

- Starboard version (use `starboard version`): 0.6.0
- Kubernetes version (use `kubectl version`): 1.17.3
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): macOS 10.15

**Comment by danielpacak** [comment]
👋 @sylus Thank you for opening this issue. What would be desired behaviour in your case? Ignoring windows nodes (or in general any tainted node) and run kube-bench only on linux nodes?

**Comment by sylus** [comment]
Yup @danielpacak i think that would be the solution i'd like to see :D

**Comment by krol3** [comment]
I'd like to test this, and try to do the fixes for this issue. 
Thanks, @sylus, It seems that kube-bench doesn’t  support windows nodes. [More details](https://github.com/aquasecurity/kube-bench/issues/624)
