### ISSUE TITLE
Take Starboard configuration from ConfigMap

### ISSUE THREAD

**Issue by jerbia** [aquasecurity/starboard#248]
Take all Starboard configuration items from ConfigMap.
This allows easier changes

**Comment by lizrice** [comment]
ConfigMap is already [supported](https://github.com/aquasecurity/starboard#configuration)

There are additional parameters we need to add. I'm converting this issue to track configuration of custom headers passed to Trivy

**Comment by lizrice** [comment]
Support running a command like `trivy client --custom-headers x-api-key:<key> --remote https://<server>/vs/v1/scan alpine`
