### ISSUE TITLE
Publish the Helm chart for Starboard operator to the Aqua OSS chart registry

### ISSUE THREAD

**Issue by danielpacak** [aquasecurity/starboard#256]
Whenever we release new version fo the operator it should be published to https://helm.aquasec.com

```
$ helm repo add aqua https://helm.aquasec.com
```

```
$ helm search repo aqua
NAME                     	CHART VERSION	APP VERSION	DESCRIPTION
aqua/harbor-scanner-aqua 	0.10.1       	0.10.0     	Harbor scanner adapter for Aqua CSP scanner
aqua/enforcer            	5.3.0        	5.3        	A Helm chart for the Aqua Enforcer
aqua/harbor-scanner-trivy	0.12.0       	0.15.0     	Harbor scanner adapter for Trivy
aqua/scanner             	5.3.0        	5.3        	A Helm chart for the Aqua Scanner CLI component
aqua/server              	5.3.0        	5.3        	A Helm chart for the Aqua Console components
```

**Comment by krol3** [comment]
I would like to help with this issue

**Comment by danielpacak** [comment]
As we discussed, instead of using Aqua Enterprise chart registry we'd like to have our own registry for all OSS projects including:
- Starboard Operator
- Harbor scanner for Aqua
- Harbor scanner for Trivy
- Trivy server

One option might be to use GitHub pages to host charts registry.

**Comment by krol3** [comment]
@danielpacak , What do you think about these improvements to the Helm chart, in another release:
- Improve app chart release
- add to artifacthub.io
