### ISSUE TITLE
Image scans fail with message unsupported MediaType: "application/vnd.docker.distribution.manifest.v1+prettyjws"

### ISSUE THREAD

**Issue by mmerrill3** [aquasecurity/starboard#259]
**What steps did you take and what happened:**
Ran starboard version 0.7.0, and received the message "unsupported MediaType: "application/vnd.docker.distribution.manifest.v1+prettyjws" when the scan job attempts to download the target image.

The image to be scanned is quay.io/bitnami/sealed-secrets-controller:v0.7.0

**What did you expect to happen:**

successful scan

**Anything else you would like to add:**

log statement

`{"level":"error","ts":1607018828.1612976,"logger":"controller.job","msg":"Scan job container","job":"security/f74eb8e5-953e-4618-88d2-f2d666094ed0","container":"sealed-secrets","status.reason":"Error","status.message":"2020-12-03T18:07:08.035Z\t\u001b[31mFATAL\u001b[0m\tunable to initialize a scanner: unable to initialize a docker scanner: 2 errors occurred:\n\t* unable to inspect the image (quay.io/bitnami/sealed-secrets-controller:v0.7.0): Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?\n\t* unsupported MediaType: \"application/vnd.docker.distribution.manifest.v1+prettyjws\", see https://github.com/google/go-containerregistry/issues/377\n\n\n","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/home/runner/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128\ngithub.com/aquasecurity/starboard/pkg/operator/controller/job.(*JobController).processFailedScanJob\n\t/home/runner/work/starboard/starboard/pkg/operator/controller/job/job_controller.go:121\ngithub.com/aquasecurity/starboard/pkg/operator/controller/job.(*JobController).Reconcile\n\t/home/runner/work/starboard/starboard/pkg/operator/controller/job/job_controller.go:62\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.3/pkg/internal/controller/controller.go:244\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.3/pkg/internal/controller/controller.go:218\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.3/pkg/internal/controller/controller.go:197\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:90"}
`

**Environment:**

- Starboard version (use `starboard version`):
0.7.0
- Kubernetes version (use `kubectl version`):
1.19.4
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc):

**Comment by mmerrill3** [comment]
Given, this is not necessarily a problem with starboard, but rather the docker implementation in use by starboard.  It only supports v2 images.

**Comment by danielpacak** [comment]
👋 @mmerrill3 Thank you for trying out Starboard. The error is related to the container image with the manifest that is not supported by [Trivy](https://github.com/aquasecurity/trivy) v0.14.0, which is the underlying vulnerability scanner used by Starboard. AFAIK we're not going to support it in Trivy so there's nothing really we can do in Starboard to fix it.
