### ISSUE TITLE
Set ownerReference for vulnerabilities resource

### ISSUE THREAD

**Issue by danielpacak** [aquasecurity/starboard#26]
By design vulnerabilities are associated with native Kubernetes workloads such as Deployments or Stateful Sets via labels and label selectors. To leverage Kubernetes Garbage Collection we can set the ownerReference for each vulnerabilities resource when we create it.

**Comment by krol3** [comment]
I'd like to help it

**Comment by danielpacak** [comment]
@krol3 To avoid conflicts, let's wait for https://github.com/aquasecurity/starboard/pull/95 to be merged
