### ISSUE TITLE
Cannot use SecurityContext

### ISSUE THREAD

**Issue by djkormo** [aquasecurity/starboard#290]
How to configure starboard via operator to use securityContext ?

k get pod,job -n starboard-operator
NAME                                             READY   STATUS                            RESTARTS   AGE
pod/16f0140e-2769-4b89-9d0e-c56c9f317bc2-4n4xm   0/1     Init:CreateContainerConfigError   0          33s

pod/starboard-operator-6759cbc887-2zzjz          1/1     Running                           0          5m36s

NAME                                             COMPLETIONS   DURATION   AGE
job.batch/16f0140e-2769-4b89-9d0e-c56c9f317bc2   0/1           33s        33s

**Error: container has runAsNonRoot and image will run as root**

**Environment:**

- Starboard version starboard-operator:0.7.1
- Kubernetes version 1.18.9
- OS (Windows 10):

**Comment by danielpacak** [comment]
👋 @djkormo Some scanners must run as root, e.g. Trivy v0.14.0 - the default vulnerability scanner integrated with Starboard Operator. Hence, we do not allow configuring SecurityContext for pods run by vulnerability scan jobs. Polaris, on the other hand, which is integrated with Starboard CLI, can run as non root.

We still have some tasks to implement least-privileged principle for other scanners, but in general SecurityContext won't be configurable, because invalid config might actually break the functionality.

**Comment by djkormo** [comment]
So maybe  you shoud prepare manifests with  rbac for service account ?

**Comment by danielpacak** [comment]
Well, we have RBAC rules for service account that is running the operator's pod and downstream scan jobs. See, for example, https://github.com/aquasecurity/starboard/blob/main/deploy/helm/templates/rbac.yaml
I don't see how is that related to SecurityContext though?

**Comment by djkormo** [comment]
Maybe I'm wrong, but I cannot see  permission like this

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: starboard-operator-psp
  namespace: starboard-operator
rules:
- apiGroups:
  - policy
  resourceNames:
  - privileged
  resources:
  - podsecuritypolicies
  verbs:
  - use

**Comment by danielpacak** [comment]
Okey so maybe without jumping into solutions straight away we should better understand what is the problem that you're trying to solve? I guess this is related to PodSecurityPolices enabled in your cluster. Could you provide more details about this setup? In particular what are the constraints that you usually put on workloads running in the cluster. Based on that we can think of RBAC config and / or SecurityContexts

**Comment by danielpacak** [comment]
@djkormo do you have any update on that? If not I'm going to close as stale issue.

**Comment by djkormo** [comment]
Let's close.
