### ISSUE TITLE
Update Contributing guides

### ISSUE THREAD

**Issue by danielpacak** [aquasecurity/starboard#31]
We should explain how to
- configure dev env
- run unit and integration tests
- fork repo and open pull requests
- use descriptive commit messages
- squash commits
- rebase PR branches
- add unit tests for new functionality

To some extent we have it described in https://github.com/aquasecurity/starboard/blob/master/HACKING.md

I don't want to copy & paste, but this one can inspire you https://github.com/projectcontour/contour/blob/main/CONTRIBUTING.md

**Comment by kichloo** [comment]
Kindly assign this issue to me.

**Comment by kichloo** [comment]
Kindly assign this issue to me.

**Comment by hillarysousa** [comment]
hey, if it's up for grabs I'd like to do this one :)

**Comment by kichloo** [comment]
Hi, UPDATE: I am working on this issue and will soon make a PR regarding it

**Comment by swapniljha001** [comment]
Is this issue already resolved?

**Comment by danielpacak** [comment]
Since we're merging the operator code from https://github.com/aquasecurity/starboard-operator into this repository I'll take this one.

**Comment by danielpacak** [comment]
I think we can close this one as we already have pretty detailed contributing guide in https://github.com/aquasecurity/starboard/blob/master/CONTRIBUTING.md
