### ISSUE TITLE
Getting started guide link is broken on homepage

### ISSUE THREAD

**Issue by aleksfront** [aquasecurity/starboard#374]
`Getting started guide` link should be fixed to head proper documentation section

![Screenshot 2021-02-02 at 13 31 58](https://user-images.githubusercontent.com/9607060/106587903-39bc4080-655b-11eb-95e1-97835e7995ef.png)

**Comment by danielpacak** [comment]
Thanks you @aleksfront for reporting that. It should be fixed now.
