### ISSUE TITLE
Call out what components work in air-gapped environments.

### ISSUE THREAD

**Issue by jimangel** [aquasecurity/starboard#39]
I assume something like Trivy needs ability to pull latest CVE DB info, but it would be great to know what does (or doesn't) work in air-gapped clusters.

Going further, there might be some additional config / docs needed for those types of environments.

**Comment by danielpacak** [comment]
Thank you for bringing this up @jimangel 

We'll update the README with prerequisites such as you mentioned. Beyond that we'll explain what are the RBAC privileges required to run Starboard CLI.

**Comment by kfox1111** [comment]
if you can run your own trivy container, you could rebuild it with up to date CVE DB info periodically. Can you specify which trivy image to use to starboard?

**Comment by danielpacak** [comment]
We've published project documentation on https://aquasecurity.github.io/starboard/v0.11.0/  
Under the Integrations menu there are pages that describe each plugin in details, e.g. [Trivy](https://aquasecurity.github.io/starboard/v0.11.0/integrations/vulnerability-scanners/trivy/).

If some information is still missing please elaborate and we'll add it.

**Comment by kfox1111** [comment]
I'm not seeing in the updated documentation how to do an airgapped database download, unless thats what the client/server mode is intended to do?

**Comment by danielpacak** [comment]
> I'm not seeing in the updated documentation how to do an airgapped database download, unless thats what the client/server mode is intended to do?

This issue wasn't about Trivy in air-gapped environments. It was about documenting requirements and constraints. What you're probably looking for is tracked under #617

**Comment by kfox1111** [comment]
ah. got it. sorry for the confusion. thanks.
