### ISSUE TITLE
Describe the VulnerabilityReport CRD so it can be used with kubectl explain command

### ISSUE THREAD

**Issue by danielpacak** [aquasecurity/starboard#409]
Provide documentation for VulnerabilityReports:

```console
$ kubectl explain vulnerabilityreports.aquasecurity.github.io
KIND:     VulnerabilityReport
VERSION:  aquasecurity.github.io/v1alpha1

DESCRIPTION:
     <empty>
```

We could provide similar docs to built-in resources and link to https://aquasecurity.github.io/starboard/latest/crds/#vulnerabilityreport for mode details and examples.

```console
$ kubectl explain svc.spec
KIND:     Service
VERSION:  v1

RESOURCE: spec <Object>

DESCRIPTION:
     Spec defines the behavior of a service.
     https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#spec-and-status

     ServiceSpec describes the attributes that a user creates on a service.

FIELDS:
   clusterIP	<string>
     clusterIP is the IP address of the service and is usually assigned randomly
     by the master. If an address is specified manually and is not in use by
     others, it will be allocated to the service; otherwise, creation of the
     service will fail. This field can not be changed through updates. Valid
     values are "None", empty string (""), or a valid IP address. "None" can be
     specified for headless services when proxying is not required. Only applies
     to types ClusterIP, NodePort, and LoadBalancer. Ignored if type is
     ExternalName. More info:
     https://kubernetes.io/docs/concepts/services-networking/service/#virtual-ips-and-service-proxies
```

**Comment by champness** [comment]
@danielpacak I'm not sure if this is possible at this time.  It looks like this was ruled out in https://github.com/kubernetes/kubernetes/issues/86800.

**Comment by danielpacak** [comment]
👋 @champness I believe that kubernetes/kubernetes#86800 is a different issue. We do not want to describe built-in `metav1.ObjectMeta` but we'd like to document other properties such as the root `VulnerabilityReport` object and / or fields defined by the `Vulnerability` struct, e.g. `Severity`.

I did a quick test and it seems to work as expected (K8s v1.20.2, client-go v0.19.2):

![describe_crd](https://user-images.githubusercontent.com/1322923/114005339-bcb18e00-985f-11eb-861a-ceee502d4a85.png)

**Comment by danielpacak** [comment]
Out of curiosity I checked what happens when we try describing the metadata object and indeed it fails (see line 101 in the code snippet below).

Our goal is to describe custom properties defined by Starboard CRDs and we can assume that everyone who's using `kubectl explain` command knows what is a K8s metadata.

![describe_metadata](https://user-images.githubusercontent.com/1322923/114006095-6f81ec00-9860-11eb-9fae-c80e0dab491b.png)

```
I0408 11:46:26.818939    4625 cr_manager.go:312] Creating CRD "vulnerabilityreports.aquasecurity.github.io"
error: CustomResourceDefinition.apiextensions.k8s.io "vulnerabilityreports.aquasecurity.github.io" is invalid: spec.validation.openAPIV3Schema.properties[metadata]: Forbidden: must not specify anything other than name and generateName, but metadata is implicitly specified
```

**Comment by danielpacak** [comment]
NB the VulnerabilityReports CRD is duplicate in `deploy/crd/vulnerabilityreports.crd.yaml` and Go struct literal used to init the CLI. We should merge #484 and only add descriptions in `deploy/crd/vulnerabilityreports.crd.yaml`.
