### ISSUE TITLE
[cli] HTML report for namespace - top 5 failed workload configuration checks

### ISSUE THREAD

**Issue by danielpacak** [aquasecurity/starboard#410]
Using Starboard CLI you can generate an HTML for a specified namespace:

```
starboard get report namespace/my-namespace > my-namespace-report.html
```

Currently, the report shows only top 5 vulnerable images by severity count.

![html_report_namespace](https://user-images.githubusercontent.com/1322923/112464394-bdc4c480-8d63-11eb-8011-d69f990e33df.png)

We'd like to add another section with the following content:

##  Top 5 failed workload configuration checks

| Name | Severity | Category | Affected Workloads |
|-------|---------|----------|--------------------|
| memoryLimitsMissing | warning | Resources | 10 |
| notReadOnlyRootFilesystem | warning | Security | 10 |
| livenessProbeMissing | warning | Health Checks | 8 |
| runAsRootAllowed | danger | Security | 7 |
| cpuRequestsMissing | warning | Resources | 6 |

We should pull and aggregate data stored as ConfigAuditReport objects.

**Comment by xyoxo** [comment]
Please assign me on this.
