### ISSUE TITLE
error message following install guide

### ISSUE THREAD

**Issue by xxradar** [aquasecurity/starboard#42]
$ starboard find vulnerabilities deployment/nginx --namespace dev -v 3
I0602 19:53:04.523020   20733 scanner.go:55] Getting Pod template for workload: Deployment/nginx
I0602 19:53:04.538831   20733 runnable_job.go:45] Creating runnable job: starboard/f46f480a-ac61-4a7e-891a-29bb21fddc3b
I0602 19:53:04.549248   20733 reflector.go:150] Starting reflector *v1.Job (30m0s) from pkg/mod/k8s.io/client-go@v0.17.5/tools/cache/reflector.go:105
I0602 19:53:04.549272   20733 reflector.go:185] Listing and watching *v1.Job from pkg/mod/k8s.io/client-go@v0.17.5/tools/cache/reflector.go:105
I0602 19:53:11.615280   20733 runnable_job.go:68] Stopping runnable job on task completion with status: Complete
I0602 19:53:11.615321   20733 runner.go:60] Stopping runner on task completion with error: <nil>
I0602 19:53:11.615334   20733 scanner.go:89] Scan job completed: starboard/f46f480a-ac61-4a7e-891a-29bb21fddc3b
I0602 19:53:11.623286   20733 scanner.go:216] Getting logs for nginx container in job: starboard/f46f480a-ac61-4a7e-891a-29bb21fddc3b
I0602 19:53:11.645638   20733 scanner.go:82] Deleting job: starboard/f46f480a-ac61-4a7e-891a-29bb21fddc3b
error: json: cannot unmarshal number into Go value of type []trivy.ScanReport

Any idea on how to solve this or pointer?

thx

**Comment by danielpacak** [comment]
Thank you for reporting this issue @xxradar Around the same time we've release new version of Trivy 0.9.0 which doesn't seem to work with Starboard. I'll see what has changed in JSON output between the two releases but in the meantime the fix would be to pin to Trivy 0.8.0 when we run the scanner.
