### ISSUE TITLE
Vulnerability Scan not working on custom images ?

### ISSUE THREAD

**Issue by masaru2604** [aquasecurity/starboard#421]
**What steps did you take and what happened:**

Vulnerability Scan not working on custom images built hosted in Azure Container Registry?

I have 2 applications in my cluster ( ReactJS single page app and a .net core api ) I've installed Starboard Operator and configured to monitor the namespaces where they are but nothing it's being scanned, I tried multiple deployments.

**What did you expect to happen:**
Scan the custom images and provide a report.

**Anything else you would like to add:**
Screenshot
[
![Untitled](https://user-images.githubusercontent.com/75610444/110254702-e04f9300-7f98-11eb-8e57-056a6941cc5a.png)
](url)

**Environment:**

- Starboard version (use `starboard version`): 0.9.2
- Kubernetes version (use `kubectl version`): 1.19.7
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): Windows 10

**Comment by danielpacak** [comment]
👋 @masaru2604 Is it a private or public Azure registry? If it's private how do you configure image pull credentials for your deployments? Are you using image pull secrets or cluster nodes are authorised to pull from the registry?

**Comment by masaru2604** [comment]
> 👋 @masaru2604 Is it a private or public Azure registry? If it's private how do you configure image pull credentials for your deployments? Are you using image pull secrets or cluster nodes are authorised to pull from the registry?

It's a private registry. I'm using the Azure Kubernetes Service and I authorized it to pull the images from ACR via Role Assignment
More details here: https://docs.microsoft.com/en-us/azure/container-registry/container-registry-auth-kubernetes

So, the vulnerability scanning works perfect on images from dockerhub, I'm using also ArgoCD in the cluster and those images are beeing scanned.

**Comment by danielpacak** [comment]
I got it. I believe that the Starboard Operator supports AKS with ACR, but we've never tested it and we've never provided documentation for Microsoft Cloud setup. We have another issue to track a similar requirement #278

**Comment by danielpacak** [comment]
Closing this one as it's related to AKS and ACR, not "custom images". Duplicate of #278
