### ISSUE TITLE
403 API rate limit exceeded when running starboard find vulnerabilities command

### ISSUE THREAD

**Issue by danielpacak** [aquasecurity/starboard#43]
Trivy downloads `trivy.db` file from GtiHub release page which is subject to rate limit. Beyond that we do not cache the DB file.

2020-06-03T08:45:29.803Z INFO Need to update DB
2020-06-03T08:45:29.803Z INFO Downloading DB...
2020-06-03T08:45:29.962Z FATAL failed to download vulnerability DB: failed to download vulnerability DB: failed to list releases: GET https://api.github.com/repos/aquasecurity/trivy-db/releases: 403 API rate limit exceeded for X.X.X.X. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) [rate reset in 32m22s]

**Comment by danielpacak** [comment]
We can add `trivy.githubToken` config key to the `starboard` ConfigMap and use it to set the `TRIVY_GITHUB_TOKEN environment variable when we create a Job for Trivy scanner. Ideally instead of ConfigMap we should have Secret, but that's a good start to make the token configurable.

**Comment by ichasco-heytrade** [comment]
Hi!
Is this working correctly?  It doesn't work for me:

```
...
trivy:
...
    githubToken: XXXXXXXXX
...
```

Error:
```
starboard-operator-6c4c4fc964-zjhj9 starboard-operator {"level":"error","ts":1629108029.9714406,"logger":"reconciler.vulnerabilityreport","msg":"Scan job container","job":"security/scan-vulnerabilityreport-997db977d","container":"783ccf48-9373-4ed8-87bd-81342768ab37","status.reason":"Error","status.message":"2021-08-16T10:00:28.150Z\t\u001b[34mINFO\u001b[0m\tNeed to update DB\n2021-08-16T10:00:28.150Z\t\u001b[34mINFO\u001b[0m\tDownloading DB...\n2021-08-16T10:00:28.360Z\t\u001b[31mFATAL\u001b[0m\tDB error: failed to download vulnerability DB: failed to download vulnerability DB: failed to list releases: GET https://api.github.com/repos/aquasecurity/trivy-db/releases: 403 API rate limit exceeded for 54.78.114.226. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) [rate reset in 45m32s]\n","stacktrace":"github.com/aquasecurity/starboard/pkg/operator/controller.(*VulnerabilityReportReconciler).reconcileJobs.func1\n\t/home/runner/work/starboard/starboard/pkg/operator/controller/vulnerabilityreport.go:332\nsigs.k8s.io/controller-runtime/pkg/reconcile.Func.Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.5/pkg/reconcile/reconcile.go:102\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.5/pkg/internal/controller/controller.go:298\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.5/pkg/internal/controller/controller.go:253\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.5/pkg/internal/controller/controller.go:214"}
```

Thanks!

**Comment by danielpacak** [comment]
> Hi!
> Is this working correctly? It doesn't work for me:
> 
> ```
> ...
> trivy:
> ...
>     githubToken: XXXXXXXXX
> ...
> ```
> 
> Error:
> 
> ```
> starboard-operator-6c4c4fc964-zjhj9 starboard-operator {"level":"error","ts":1629108029.9714406,"logger":"reconciler.vulnerabilityreport","msg":"Scan job container","job":"security/scan-vulnerabilityreport-997db977d","container":"783ccf48-9373-4ed8-87bd-81342768ab37","status.reason":"Error","status.message":"2021-08-16T10:00:28.150Z\t\u001b[34mINFO\u001b[0m\tNeed to update DB\n2021-08-16T10:00:28.150Z\t\u001b[34mINFO\u001b[0m\tDownloading DB...\n2021-08-16T10:00:28.360Z\t\u001b[31mFATAL\u001b[0m\tDB error: failed to download vulnerability DB: failed to download vulnerability DB: failed to list releases: GET https://api.github.com/repos/aquasecurity/trivy-db/releases: 403 API rate limit exceeded for 54.78.114.226. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) [rate reset in 45m32s]\n","stacktrace":"github.com/aquasecurity/starboard/pkg/operator/controller.(*VulnerabilityReportReconciler).reconcileJobs.func1\n\t/home/runner/work/starboard/starboard/pkg/operator/controller/vulnerabilityreport.go:332\nsigs.k8s.io/controller-runtime/pkg/reconcile.Func.Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.5/pkg/reconcile/reconcile.go:102\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.5/pkg/internal/controller/controller.go:298\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.5/pkg/internal/controller/controller.go:253\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.5/pkg/internal/controller/controller.go:214"}
> ```
> 
> HELM Chart version: `0.6.0`
> 
> Thanks!

@ichasco-heytrade from the snippet you shared I cannot tell whether the token is configured properly or not. But make sure that it is stored as the value of the `trivy.githubToken` key in the `starboard-trivy-config` secret in the operator namespace. See [Trivy Settings](https://aquasecurity.github.io/starboard/v0.11.0/integrations/vulnerability-scanners/trivy/#settings) for more details.

**Comment by ichasco-heytrade** [comment]
Hi @danielpacak, thanks for reply.
No it isn't stored in `starboard-trivy-config`. I don't know why. 

The full trivy configuration is:
```
  trivy:
    imageRef: docker.io/aquasec/trivy:0.19.2
    mode: Standalone
    serverURL:
    httpProxy:
    httpsProxy:
    githubToken: XXXXXXXXXXXXXXXx
    noProxy:
    severity: HIGH,CRITICAL
    resources:
      requests:
        cpu: 100m
        memory: 100M
      limits:
        cpu: 500m
        memory: 500M

```

**Comment by danielpacak** [comment]
I guess that what you've shared is values.yaml, which is the default config of the Helm chart. Helm values are transformed into K8s ConfigMap and Secrets objects named `starboard-trivy-config`. See https://github.com/aquasecurity/starboard/blob/main/deploy/helm/templates/config.yaml#L28 for more details.

Apparently we do not support setting `trivy.githubToken` config property via Helm values. You'd have to do that manually by patching the `starboard-trivy-config` Secret. Otherwise a change request would be required to implement what you intended.

**Comment by ichasco-heytrade** [comment]
But didn't this PR fix that?
https://github.com/aquasecurity/starboard/pull/172

Maybe this issue should not be closed until this is implemented?

**Comment by danielpacak** [comment]
> But didn't this PR fix that?
> #172
> 
> Maybe this issue should not be closed until this is implemented?

In #172 we defined trivy.githubToken config param and added logic to read it from secret and it's working fine.

In your case we're talking about enhancement to Helm chart installer, which is related but a different story.

**Comment by ichasco-heytrade** [comment]
A ok understood thanks!

**Comment by danielpacak** [comment]
@ichasco-heytrade In 6f580c6 we added Helm value to configure GitHub token for Trivy plugin. Once we release it you'll be able to install the operator as follows:

```
export GITHUB_TOKEN="****"

helm install starboard-operator deploy/helm \
  --namespace starboard-system --create-namespace \
  --set="targetNamespaces=default" \
  --set="trivy.githubToken=$GITHUB_TOKEN"
```

**Comment by ichasco-heytrade** [comment]
Perfect, Thank you very much :)
