### ISSUE TITLE
Bump up Polaris from v3.0 to v3.2

### ISSUE THREAD

**Issue by danielpacak** [aquasecurity/starboard#433]
Starboard is using Polaris (quay.io/fairwinds/polaris:3.0) as a configuration audit scanner. There's a new version that we should test for compatibility and integrate. The goal is to:
- [ ] Check what has changed in Polaris 3.2 and make sure that the output JSON is compatible with the parser that we've implemented.
- [ ] Update deployment descriptors (YAML) and Go code to refer to Polaris:3.2

**Comment by champness** [comment]
@danielpacak May I grab this one?
