### ISSUE TITLE
Add manually triggered GitHub Actions workflow to test Helm chart

### ISSUE THREAD

**Issue by danielpacak** [aquasecurity/starboard#460]
Before each release we have to manually test and validate Helm chart templates. Instead we could automated that and run such tests on GitHub. We'd start with a manual trigger and later on we could integrate it with the release workflow.

The steps could be:
- Build Starboard Operator to container image (a la make docker-build)
- helm install starboard-operator deploy/helm with default or custom values
- Wait for the operator pod until it's spun up
- Do a sanity check by asserting that security reports are generated and saved in custom resources

**Comment by xyoxo** [comment]
Some suggestions:
- `helm-install` `helm-uninstall` make commands to install/unistall helm chart. 
- Some values can be modified/overridden by env var while installing the chart using make command.
- The make command will also wait for the operator pod to be ready.
- Update the integration test suite code to support external operator (i.e. helm charts).

**Comment by krol3** [comment]
@danielpacak  with this PR we are testing the helm chart. https://github.com/aquasecurity/starboard/pull/829
any improvement for this current issue could we do ?

**Comment by danielpacak** [comment]
Since we have already integrated Helm chart tests in the PR validation workflow in 8f637cfd5c9dd64f56a2ab8e0ee81cc85c174b7c we can close this issue.

If we want to further improve we could do that directly with a new PR or discuss in a separate thread.
