### ISSUE TITLE
AWS: Error creating Jobs - Label has more than 63 characters

### ISSUE THREAD

**Issue by dschunack** [aquasecurity/starboard#518]
**What steps did you take and what happened:**
The job creation for kube-Bench scan causes an error. Too many characters for the label if you run it on AWS. 

**"error":"creating job: Job.batch \"scan-kubebenchreports-ip-100-96-5-57.eu-central-1.compute.internal\" is invalid: spec.template.labels: Invalid value: \"scan-kubebenchreports-ip-100-96-5-57.eu-central-1.compute.internal\": must be no more than 63 characters"**

`
{"level":"error","ts":1619006819.8919835,"logger":"controller-runtime.manager.controller.node","msg":"Reconciler error","reconciler group":"","reconciler kind":"Node","name":"ip-100-96-5-57.eu-central-1.compute.internal","namespace":"","error":"creating job: Job.batch \"scan-kubebenchreports-ip-100-96-5-57.eu-central-1.compute.internal\" is invalid: spec.template.labels: Invalid value: \"scan-kubebenchreports-ip-100-96-5-57.eu-central-1.compute.internal\": must be no more than 63 characters","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/home/runner/go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.2/pkg/internal/controller/controller.go:267\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.2/pkg/internal/controller/controller.go:235\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.1\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.2/pkg/internal/controller/controller.go:198\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.UntilWithContext\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:99"}
`

**What did you expect to happen:**
Creation of the Job

**Environment:**

- Starboard version (use `starboard version`): v0.10.0
- Kubernetes version (use `kubectl version`): 
`
Client Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.4-dirty", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"dirty", BuildDate:"2021-03-15T09:58:13Z", GoVersion:"go1.16.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
`
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): macOS 11.2

**Comment by danielpacak** [comment]
Thank you for reporting the issue @dschunack We've fixed it by hashing the name of a node so the scan job is named as `scan-cisbenchmark-<hash>`. The fix is available in v0.10.1
