### ISSUE TITLE
feat: vulnerability rescan of K8s workloads based on report TTL

### ISSUE THREAD

**Issue by danielpacak** [aquasecurity/starboard#537]
This is a placeholder to specify how such functionality can be implemented

**Comment by glimpsec** [comment]
A nightly rescan, specifically with Trivy, would help us recognise newly discovered CVE's in production workloads. If Trivy only scans on pod change, older pods won't have a recent scan. Old pods have an increased risk of running vulnerable images.

We're excited about the Starboard project, and this feature would make us reconsider it for production use.

**Comment by kfox1111** [comment]
This would be useful. when we started playing around, we noticed that deleting the VulnerabilityReport object caused it to immediately rescan when using the operator. Maybe all that is needed is a cronjob that deletes all VulnerabilitieReports.

**Comment by henrysachs** [comment]
I know this is kind of bad practice but is there any update on the plans of this? The issue is open since april and I just wanted to know if this is still on the "roadmap". If so what would be the best way to implement this? Maybe i can kind of support right here?

**Comment by danielpacak** [comment]
Just to update readers on a current status we are working on a few enhancements to vulnerability scanning to make it more efficient. This may change the way we persist VulnerabilityReport instances and impact a lifecycle of each report. On the other hand, such braking changes will be probably introduced behind feature gates. What's more, the mechanism for rescanning could be agnostic to the lifecycle of VulnerabilityReport object.

Therefore, if you want to help with general rescanning concept we'd appreciate any high level overview for the solution that's compatible with K8s controller pattern and current architecture of Starboard. We'll take it from there.

**Comment by kfox1111** [comment]
+1

Is there a process that we can use to help? Something similar to a KEP? Then we could comment on the general design and help enhance it.

**Comment by danielpacak** [comment]
We haven't introduced any formal proposal workflow at this stage such as KEP. We can transfer this issue to discussion and start from there. Public GDoc with a few diagrams would work as well.

I know we weren't consistent but I'd prefer discussion design and idea brainstorming under GitHub discussion. Issues are good for bugs and finite well defined tasks. Otherwise we'll keep them opened for way too long.

**Comment by kfox1111** [comment]
GDoc would allow for inline comments, which may be helpful for quicker iteration. Maybe we work there for a little while and then bring it to discussions?

**Comment by danielpacak** [comment]
GDoc for getting started would do the job. However, for other design tasks we decided (last week) to host them under /docs/design

**Comment by NissesSenap** [comment]
Created a initial PR on how we could solve this issue: https://github.com/aquasecurity/starboard/pull/863 
Hopefully it's a good base for a discussion.

**Comment by danielpacak** [comment]
I have update the title of this issue to narrow down the scope to vulnerability scanning so we can actually resolve it when it is implemented. Other types of reports should be considered separately as they have different lifecycle.
