### ISSUE TITLE
Add annotations to scan jobs spawned by Starboard

### ISSUE THREAD

**Issue by danielpacak** [aquasecurity/starboard#539]
See #356

**Comment by krol3** [comment]
I'd like to help with this issue.

**Comment by yashvardhan-kukreja** [comment]
Hi @krol3 @danielpacak 
Do you folks mind if I pick this issue up if this issue hasn't been progressed upon yet? 😊

**Comment by krol3** [comment]
@yashvardhan-kukreja  You can take it

**Comment by yashvardhan-kukreja** [comment]
Thanks @krol3 :D

**Comment by yashvardhan-kukreja** [comment]
@danielpacak Here if I am not wrong, the user (who raised the discussion) wanted to provide custom annotations in runtime.

So, I am thinking something like a new argument called, say, `custom-scanjob-annotations` (we can go with a better name :P) which the user would be able to provide as a part of the `starboard scan vulnerabilityreports` command. Multiple annotations can be just added in a comma-separated manner which is pretty k8s compliant too.

For example, `starboard scan vulnerabilityreports foo --custom-scanjob-annotations kube2iam.rolearn=arn:aws:iam:bla,custom-annotation-key1=value1`

This will ensure to annotate the scanjob (and the pods it spins up) with the annotations:
`kube2iam.rolearn: arn:aws:iam:bla` and `custom-annotation-key1: value1`

**Comment by danielpacak** [comment]
👋 @yashvardhan-kukreja I think command line args will do the job for Starboard CLI but we have to provide the same behavior for Starboard Operator. Both read config from the *starboard* ConfigMap (see https://aquasecurity.github.io/starboard/v0.10.3/settings/). So IMO it would be better to add custom annotations to the *starboard* ConfigMap. WDYT? This will allow the following flow:

```
# 1. Init starboard
starboard init
# 2. Patch starboard ConfigMap to customize config, e.g. kubectl patch cm starboard -n starboard ...
./add-custom-annotaions.sh
# 3. Scan for vulnerabilities
starboard scan vulnerabilityreports deploy/nginx
```

**Comment by yashvardhan-kukreja** [comment]
Yep, Good point. Let's go ahead with making the user provide custom annotations via the ConfigMap.

Although, I am still a lil skeptical about running a shell script like "add-custom-annotations.sh" to patch the cm.
Doesn't look the most UX-friendly, in my opinion.

May be, some other cleaner approach can be used?
Like for example, a starboard command like `starboard configure-custom-annotations annotation1=value1,annotation2=value2` and behind the scenes, this command will patch the cm.

This command can be run after starboard init hence, replacing the bash script to patch the cm.
And technically, the user can still use the shell script if they want to, hence, providing the user the flexibility as well.

So, wdyt about this approach?

PS: This approach just came on top of my mind. We can even think of some cleaner or more efficient approach than this. But yeah, for now, I'd love to know what do you think of this approach of the `starboard configure-custom-annotations` command

**Comment by danielpacak** [comment]
The ./add-custom-annotations.sh was just a placeholder to indicate that a user will have a chance to customise default config params and add annotations. Whether it's kubectl patch or starboard subcommand is secondary. We can always improve the UX in subsequent PRs. For UX / editing config I'd leverage the existing `starboard config` command, which currently works in read-only mode.

**Comment by yashvardhan-kukreja** [comment]
Got it, sounds good 👍🏼

**Comment by yashvardhan-kukreja** [comment]
👋 @danielpacak I have made the PR dealing with this feature. One thing to note here is that I haven't added any functionality/sub-command around making the user input the custom-annotations in the first place, as that topic is still under discussion.

Meaning, as of the current state of the PR, the user (or us while testing) would have to manually patch the starboard configmap with the custom annotations.

For further reference around this, you can checkout the description of the above PR.

Thanks!

**Comment by danielpacak** [comment]
We prefer smaller tasks / PRs. Do one thing at a time and then incrementally improve in the subsequent PR. Otherwise we're dealing with giant PRs that are hard to comprehend and validate. That said, it's perfectly find to add new config param that's recognised by Starboard and document that it has to be patched manually. In the next iteration we might think of flags or command-line args.

**Comment by yashvardhan-kukreja** [comment]
Sure, Daniel. Will make sure to cook smaller PRs at one time from next time onwards.

Speaking of the functionality in which custom annotations will be fed:
For CLI: Using the `starboard config` command to feed the custom annotations
For the Operator: the custom annotations can be fed via kubectl patch or via values.yaml at the time of helm installation.

Is that fine?

**Comment by jeremeb** [comment]
Could we also add in the ability to update Trivy pod resource limits requested in !572?

**Comment by danielpacak** [comment]
> Could we also add in the ability to update Trivy pod resource limits requested in #572?

According to contribution guidelines and to facilitate maintenance / code review we'll add resource limits and requests in a separate PR.

**Comment by yashvardhan-kukreja** [comment]
Hi @danielpacak , I guess we can create another issue to work upon the functionality/capability to allow the user to feed the scanJob annotations comfortably instead of doing so via kubectl patching the configmap.

We can track the discussion further around this topic here https://github.com/aquasecurity/starboard/discussions/595 :)

**Comment by danielpacak** [comment]
I'd start with the discussion if we really need such functionality. If you look at the numer of available configuration settings maintaining them as CLI flags might be more expensive than just patching a ConfigMap. At least at this stage of this project. On the other hand there are structured config params such as annotations, tolerations, resource requests/limits that are hard to represent as CLI args / flags. We could use a discussion / thread to propose a few possible options for CLI before we jump on coding all that.

**Comment by yashvardhan-kukreja** [comment]
Yep, that's what I was conveying too that we can keep track of the ideas around this functionality on that "Discussion" thread which I created.
I was just exemplifying when I suggested that we could feed scan job annotations via cli args 😊
