### ISSUE TITLE
feat(trivy): Pass additional settings to Trivy client

### ISSUE THREAD

**Issue by danielpacak** [aquasecurity/starboard#541]
According to #337 we should add the following arguments to Trivy settings and pass them down to the scan job's command:
- [ ] `ignore-unfixed` - display only fixed vulnerabilities
- [ ] `ignorefile` - specify .trivyignore file 
- [ ] `skip-files` - specify the file path to skip traversal

**Comment by xyoxo** [comment]
Please assign me
