### ISSUE TITLE
[cli] Run Kube-bench on individual nodes

### ISSUE THREAD

**Issue by danielpacak** [aquasecurity/starboard#543]
See #108 

The scan ciskubebenchreports command should accept a list of node names to scan:

```
starboard scan ciskubebenchreports node-worker-1 node-worker-2 node-control-plane
```

It should fallback to scan all nodes if names where not specified:

```
starboard scan ciskubebenchreports
```

**Comment by krol3** [comment]
I'd like to help with this issue.
