### ISSUE TITLE
Output init manifests

### ISSUE THREAD

**Issue by billyshambrook** [aquasecurity/starboard#55]
**Describe the problem/challenge you have**

To install starboard via GitOps, we need the YAML manifests to install. Would be great if the init command could optionally just output the manifests to stdout.

**Describe the solution you'd like**

**Anything else you would like to add:**

Happy to help with a PR if this sounds good and there's a preferable cmd line argument to trigger this (e.g. `starboard manifests`)

**Environment:**

- Starboard version (use `starboard version`):
- Kubernetes version (use `kubectl version`):
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc):

**Comment by danielpacak** [comment]
Thank you @billyshambrook for bringing the GitOps use case. I think it's reasonable to allow getting the manifests in the init command as you described. To some extent it's also related to #23 

I'd suggest adding the `--dry-run` and `--output` flags to the existing init command:

```
$ starboard init --dry-run -o yaml
```

We want to stay as close to the kubectl syntax as possible, so the above mentioned command would resemble a build-in kubectl commands:

```
 $ k create deploy nginx --image nginx:1.16 --dry-run -o yaml
```

WDYT? If that sound's good I'm happy to assign you @billyshambrook to this one.

**Comment by shaunmclernon** [comment]
@danielpacak I have been digging around the code on this one.

Based on the brief above, I am planning on possibly breaking this up into 2 PRs (1 for the dry-run and the other for yaml generation). I propose to mimic the kubectl behaviour for dry-run to show which objects are to be created (it is sort of an extension to work done in #164)

Currently, I have the following resources working in dry-run mode:

> $ starboard init --dry-run
Creating CRD "vulnerabilityreports.aquasecurity.github.io" (dry run)
Creating CRD "ciskubebenchreports.aquasecurity.github.io" (dry run)
Creating CRD "kubehunterreports.aquasecurity.github.io" (dry run)
Creating CRD "configauditreports.aquasecurity.github.io" (dry run)
Creating Namespace "starboard" (dry run)
Creating ConfigMap "starboard/starboard" (dry run)

Investigating the service account, cluster role and cluster role binding (and the relationship between #23)  

and obviously the YAML objects when -o yaml is included.

WDYT? Does that sound like a reasonable approach?  If so I am happy for you to assign it to me.

**Comment by danielpacak** [comment]
> @danielpacak I have been digging around the code on this one.
> 
> Based on the brief above, I am planning on possibly breaking this up into 2 PRs (1 for the dry-run and the other for yaml generation). I propose to mimic the kubectl behaviour for dry-run to show which objects are to be created (it is sort of an extension to work done in #164)
> 
> Note: That should address the concern that Duffie mentioned in [TGI Kubernetes 121: Starboard](https://www.youtube.com/watch?v=P_QZtZJAZyU)
> 
> Currently, I have the following resources working in dry-run mode:
> 
> > $ starboard init --dry-run
> > Creating CRD "vulnerabilityreports.aquasecurity.github.io" (dry run)
> > Creating CRD "ciskubebenchreports.aquasecurity.github.io" (dry run)
> > Creating CRD "kubehunterreports.aquasecurity.github.io" (dry run)
> > Creating CRD "configauditreports.aquasecurity.github.io" (dry run)
> > Creating Namespace "starboard" (dry run)
> > Creating ConfigMap "starboard/starboard" (dry run)
> 
> Investigating the service account, cluster role and cluster role binding (and the relationship between #23)
> 
> and obviously the YAML objects when -o yaml is included.
> 
> WDYT? Does that sound like a reasonable approach? If so I am happy for you to assign it to me.

@shaunmclernon I think it's reasonable approach to implement `--dry-run` flag in one PR and then follow up with another PR to output YAML.

Regarding the output we can maybe make it even closer to the `kubectl` by printing the fully qualified resource name as prefix. WDYT?

```
k create deploy tomcat --image tomcat:8 --dry-run=client
deployment.apps/tomcat created (dry run)
```

**Comment by danielpacak** [comment]
This issue has gone stale but for GitOps we provide Starboard Operator with static YAML, Helm chart, and OLM installers. Feel free to reopen if you want to contribute and have it also done for Starboard CLI.
