### ISSUE TITLE
error: [metadata.labels: Invalid value: "123456789012345678901234567890123456789012345678901234567890123-57f6c7cffd": must be no more than 63 characters

### ISSUE THREAD

**Issue by danielpacak** [aquasecurity/starboard#559]
**What steps did you take and what happened:**

```
kubectl create deploy 123456789012345678901234567890123456789012345678901234567890123 --image nginx:1.16
```

```console
$ kubectl tree deploy 123456789012345678901234567890123456789012345678901234567890123
NAMESPACE  NAME                                                                                     READY  REASON  AGE
default    Deployment/123456789012345678901234567890123456789012345678901234567890123               -              13s
default    └─ReplicaSet/123456789012345678901234567890123456789012345678901234567890123-57f6c7cffd  -              13s
default      └─Pod/1234567890123456789012345678901234567890123456789012345678bzfvp                  True           13s
```

```console
$ kubectl starboard scan configauditreports ReplicaSet/123456789012345678901234567890123456789012345678901234567890123-57f6c7cffd -v 3
I0510 16:43:33.064555   22017 scanner.go:53] Getting Pod template for workload: {ReplicaSet 123456789012345678901234567890123456789012345678901234567890123-57f6c7cffd default}
I0510 16:43:33.066606   22017 scanner.go:60] Scanning with options: {ScanJobTimeout:0s DeleteScanJob:true}
I0510 16:43:33.066648   22017 runner.go:79] Running task and waiting forever
I0510 16:43:33.066688   22017 runnable_job.go:76] Creating job "starboard/6754af7c-672b-402e-8c6b-a50c64573697"
I0510 16:43:33.069480   22017 runner.go:83] Stopping runner on task completion with error: creating job: Job.batch "6754af7c-672b-402e-8c6b-a50c64573697" is invalid: [metadata.labels: Invalid value: "123456789012345678901234567890123456789012345678901234567890123-57f6c7cffd": must be no more than 63 characters, spec.template.labels: Invalid value: "123456789012345678901234567890123456789012345678901234567890123-57f6c7cffd": must be no more than 63 characters]
error: running scan job: creating job: Job.batch "6754af7c-672b-402e-8c6b-a50c64573697" is invalid: [metadata.labels: Invalid value: "123456789012345678901234567890123456789012345678901234567890123-57f6c7cffd": must be no more than 63 characters, spec.template.labels: Invalid value: "123456789012345678901234567890123456789012345678901234567890123-57f6c7cffd": must be no more than 63 characters]
```

**What did you expect to happen:**

The ConfigAuditReport named `replicaset-123456789012345678901234567890123456789012345678901234567890123-57f6c7cffd` has been created in the default namespace

**Anything else you would like to add:**

The main problem here is that we're trying to label the scan job with a value that exceeds 63 characters, i.e.:

```
starboard.resource.kind=ReplicaSet
starboard.resource.namespace=default
starboard.resource.name=123456789012345678901234567890123456789012345678901234567890123-57f6c7cffd
```

Even if that worked the same set of labels would be used for ConfigAuditReport

**Environment:**

- Starboard version (use `starboard version`): v0.10.1
- Kubernetes version (use `kubectl version`): any
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): any

**Comment by yashvardhan-kukreja** [comment]
Yep, so let's first of all decide how do we want to treat labels with >63 chars.

- Should we just truncate them to 62 chars and then, suffix that truncated string with `*` to signify that it got truncated. For example, say, there's a deployment with the name `......abcde` (65 character name ending with abcde) 
For that, starboard can't utilise the full name as the label value would be >63 chars. Hence, starboard can instead use the label value as `......ab*` (name truncated to 62 chars and suffixed with *)
- [not good UX though] Simply throw an error (prettified) whenever a user does a starboard scan for resources with name longer than 63 chars.

I suggest the first approach as it is flexible, non-restrictive and even descriptive enough (via the `*`) to convey the user that the Deployment/ReplicaSet name was truncated for the sake of labels.

**Comment by yashvardhan-kukreja** [comment]
But there is an edge case in that situation, and that is say there are two deployments: `.......abcde` and `......abcdx` (both of 65 chars). For both of them, the truncated label value would be `......ab*` and if Starboard (behind the scenes), is making use of the label value programmatically to take job-level decisions then, thats gonna cause problems because it won't be able to identify between those 2 deployments' reports due to the same truncated labels.

So, to deal with that kind of scenario (if that's a legit concern), we can make use of annotations as if I recall correctly, annotations can hold data upto 253 or 254 characters.

**Comment by yashvardhan-kukreja** [comment]
Hi @danielpacak , any ideas or suggestions around the approaches I mentioned above? :)

**Comment by danielpacak** [comment]
We bumped into a similar issue while working on config audit for Roles and ClusterRoles (#644). A Role or ClusterRole may contain special characters such as colon (`:`) that cannot be used as label value. Therefore, we came up with the following fallback mechanism to identify security reports:
1. If the resource name is a valid label value it works as is.
2. However, if the resource name is not valid label value we calculate a deterministic hash of name and use it as the value of the `starboard.resource.name-hash` label and store the original name in the `starboard.resource.name` annotation. This way we can encode any K8s resource as a set of labels and annotations and take advantage of label selectors if needed.

#### ConfigAuditReport for the 123456789012345678901234567890123456789012345678901234567890123-57f6c7cffd ReplicaSet

```yaml
apiVersion: aquasecurity.github.io/v1alpha1
kind: ConfigAuditReport
metadata:
  name: replicaset-78c49bcf47
  namespace: default
  labels:
    plugin-config-hash: 9657c9b65
    resource-spec-hash: 7cb64cb677
    starboard.resource.kind: ReplicaSet
    starboard.resource.name-hash: 78c49bcf47
    starboard.resource.namespace: default
  annotations:
    starboard.resource.name: 123456789012345678901234567890123456789012345678901234567890123-57f6c7cffd
  creationTimestamp: "2021-08-24T09:05:03Z"
  generation: 1
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: false
    controller: true
    kind: ReplicaSet
    name: 123456789012345678901234567890123456789012345678901234567890123-57f6c7cffd
    uid: d3c26d8e-ccb5-4da5-8a44-fdc5595ec970
```

#### ConfigAuditReport for the nginx-6d4cf56db6 ReplicaSet

```yaml
apiVersion: aquasecurity.github.io/v1alpha1
kind: ConfigAuditReport
metadata:
  name: replicaset-nginx-6d4cf56db6
  namespace: default
  labels:
    plugin-config-hash: 9657c9b65
    resource-spec-hash: 7cb64cb677
    starboard.resource.kind: ReplicaSet
    starboard.resource.name: nginx-6d4cf56db6
    starboard.resource.namespace: default
  creationTimestamp: "2021-08-24T09:03:57Z"
  generation: 1
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: false
    controller: true
    kind: ReplicaSet
    name: nginx-6d4cf56db6
    uid: 85d09078-bb85-465f-856c-8f35e6ffcf0d
  resourceVersion: "7007"
  uid: ccad8131-42db-44e4-b480-10d269dd3f34
```
