### ISSUE TITLE
Using custom Trivy image

### ISSUE THREAD

**Issue by BostjanBozic** [aquasecurity/starboard#56]
**Describe the problem/challenge you have**

As my environment is running without external access, I have to use images that are available in internal repository. Currently there is no option to specify custom Trivy image used for security scanning.

**Describe the solution you'd like**

It would be great to have flag when you run e.g. `kubectl starboard find vunlerabilities` to specify custom image.

**Anything else you would like to add:**

It would be great to have that flexibility with every image that is used.

**Environment:**

- Starboard version (use `starboard version`): 0.2.1
- Kubernetes version (use `kubectl version`): 1.11.0
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): RHEL 7.7.

**Comment by danielpacak** [comment]
> Hi,
> I am here for the same reason but I use an internal Artifactory for my application images.
> When running Starboard scan I get the following error:
> 
> > error: running scan job: job failed: BackoffLimitExceeded: Job has reached the specified backoff limit
> 
> I described the POD and I think the problem is that it can pull the Trivy images but it cannot pull my internal images that are stored on Artifacry.
> 
> I have a secret in the namespace that contains the docker config with the login details but nowhere to specify the ImagePullSecret or a way to mount it to POD for it to use.

@TalZiv Starboard looks up image pull secrets set on a Pod or Service Account level. So you don't have to specify the name of the secret as arg or flag to `find vulnerabilities` command.

In your case, do you specify ServiceAccountName for the workload that you're scanning? Is it an unmanaged Pod or Kubernetes controller such as Deployment or ReplicaSet?

**Comment by danielpacak** [comment]
With the current generic `starboard` ConfigMap created by the `init` command we can define a configuration key for Trivy image reference (`trivy.imageRef`) with the default value of `docker.io/aquasec/trivy:0.9.2'

If for some reason you want to change that value you could do that by patching the `starboard` ConfigMap before you run a scan job.

**Comment by BostjanBozic** [comment]
Sounds good, works as expected, thank you!
It would still be great to have option to specify default image either by init or find command.
