### ISSUE TITLE
Automate krew plugin updates

### ISSUE THREAD

**Issue by danielpacak** [aquasecurity/starboard#58]
**Describe the problem/challenge you have**

Each time there's a new release of Starboard CLI, we have to bump up versions and checksums in the krew manifest and open a PR to the krew-index repository. This is repetitive and mundane task for us and krew-index maintainers.

**Describe the solution you'd like**

Integrated [krew-release-bot](https://krew.sigs.k8s.io/docs/developer-guide/release/automating-updates/) with the GitHub Actions release workflow.

**Anything else you would like to add:**

IIRC We have to submit the initial manifest to krew-index manually, i.e. we can work on that only after https://github.com/kubernetes-sigs/krew-index/pull/647/files is merged.

**Environment:**

- Starboard version (use `starboard version`):
- Kubernetes version (use `kubectl version`):
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc):

**Comment by krol3** [comment]
I'd like to help with this issue.

**Comment by evalsocket** [comment]
Hey, @krol3 It looks pretty simple and easy. I also have some idea about krew. Can this assign to me if you are not working on it

**Comment by krol3** [comment]
@evalsocket  I submitted the PR, could you take a look? If I'm missing something.
