### ISSUE TITLE
scan-vulnerabilityreport Job OOMKilled

### ISSUE THREAD

**Issue by goroi** [aquasecurity/starboard#619]
starboard-operator configured to use trivy 0.18.3 image insted of default trivy 0.16.0.

Some containers can not be scanned due to OOMKilled for the jobs.

 [memory resources predefined ](https://github.com/aquasecurity/starboard/blob/main/pkg/plugin/trivy/plugin.go#L30).
 
 Are you planning to expose job resource limits so that the user can set upper limits ?

**Environment:**

- Starboard version (use `starboard version`): 0.10.3
- Kubernetes version (use `kubectl version`): 1.20.2
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): Ubuntu 19.10

**Comment by danielpacak** [comment]
👋 Trivy v0.18.3 adds support for Go and Java scanning and therefore requires more resources that what is currently hardcoded for vulnerability scan job created by Starboard. We do have #572 to make resource requests and resource limits configurable so I'll close this one as duplicate.
