### ISSUE TITLE
confusing name syntax in vulnerability report output

### ISSUE THREAD

**Issue by dominicpg** [aquasecurity/starboard#632]
This seems a cosmetic issue though, I am reporting this to get fixed. Stadboard detects and return confusing name syntax when queried over starboard kubectl plugin.

$ kubectl run testpod --image=nginx:1.20 
pod/testpod created

Name in output is "pod-testpod-testpod" while the name of original pod is "testpod"

$ kubectl get vuln -o wide 
NAME                  REPOSITORY      TAG    SCANNER   AGE   CRITICAL   HIGH   MEDIUM   LOW   UNKNOWN
pod-testpod-testpod   library/nginx   1.20   Trivy     2s    3          22     10       110   0

$ starboard version
Starboard Version: {Version:0.10.3 Commit:5bd33431a239b98be4a3287563b8664a9b3d5707 Date:2021-05-14T12:20:34Z}

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:53:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}

OS version: kubectl on Fedora 33,  Master/worker nodes are on centos8.4

**Comment by danielpacak** [comment]
As explained on [Custom Resource Definitions - VulnerabilityReports](https://aquasecurity.github.io/starboard/v0.10.3/crds/#vulnerabilityreport) we use the `<workload kind>-<workload name>-<container name>` convention to name instances of VulnerabilityReport resources.

There are two reasons for that:
1. You can create a Deployment and (theoretically) name it `testpod`:
   ```
   kubectl create deploy testpod --image=nginx:1.20
   ```
   Without workload prefix, e.g. pod-, replicaset-, statefulset- you'll have a naming collision.
2. A pod (or workload in general) can have multiple containers with different image references. A VulnerabilityReport holds vulnerability items for a given image reference. Hence, we suffix container name.

I hope this helps. I also know that naming is hard so if you have a better idea, given above mentioned requirements, please share with us!
