### ISSUE TITLE
Define resource requests and limits on scan jobs

### ISSUE THREAD

**Issue by danielpacak** [aquasecurity/starboard#64]
**Describe the problem/challenge you have**

Currently the scan jobs do not set resource requests and limits. In some environments this might prevents scanners from running.

**Describe the solution you'd like**

Each scanner job should define resource requests and limits.

**Anything else you would like to add:**

Consider how to make the limits configurable with flags or Starbor config map?

**Environment:**

- Starboard version (use `starboard version`): 0.2.1
- Kubernetes version (use `kubectl version`): Any
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): Any

**Comment by krol3** [comment]
I could help settings default resource limits in the pod definition.
