### ISSUE TITLE
Notarize starboard through Apple Developer channel

### ISSUE THREAD

**Issue by danielpacak** [aquasecurity/starboard#69]
**Describe the problem/challenge you have**

On macOS running starboard CLI requires adding the binary to security exceptions.

**Describe the solution you'd like**

We should notarize our binaries as trusted provider and integrate such process with GoReleaser

**Anything else you would like to add:**

N/A

**Environment:**

- Starboard version (use `starboard version`): 0.2.1
- Kubernetes version (use `kubectl version`): Any
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): macOS

**Comment by lizrice** [comment]
On consideration it doesn't seem worth doing this at present, it doesn't appear that other Kubernetes tools go through this process
