### ISSUE TITLE
Starboard could provide better error reporting when jobs fail

### ISSUE THREAD

**Issue by DaveTCode** [aquasecurity/starboard#70]
**What steps did you take and what happened:**

`starboard kube-bench` hangs if the jobs fail due to admissions controllers

Specifically I ran `starboard kube-bench` and the command "hung" (i.e. no new prompt and no logs)

Checking `kubectl describe jobs -n starboard cb61d98b-bd1e-47fa-8ed7-efd5baee3f31` I saw 

```
Warning  FailedCreate  36s (x3 over 66s)  job-controller  Error creating: pods "cb61d98b-bd1e-47fa-8ed7-efd5baee3f31-" is forbidden: unable to validate against any pod security policy: [spec.securityContext.hostPID: Invalid value: true: Host PID is not allowed to be used spec.volumes[0]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[1]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[2]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[3]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[4]: Invalid value: "hostPath": hostPath volumes are not allowed to be used]
```

which is obviously my fault for not applying a more permissive policy to the starboard namespace but I think starboard cli could do a better job of reporting that failure.

**What did you expect to happen:**

Any sort of error, ideally telling me what the issue was.

**Anything else you would like to add:**

Thanks for this tool! In the middle of security auditing at the moment and it's making my life _way_ easier.

**Environment:**

- Starboard version (use `starboard version`): Starboard Version: {Version:0.2.1 Commit:02c0c55260c0331c590602dba624819813c97d64 Date:2020-06-05T23:15:17Z}
- Kubernetes version (use `kubectl version`): 1.18.3 client talking to 1.17.6 server
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): Windows 10 & Ubuntu 20.04 (wsl2)

**Comment by danielpacak** [comment]
Thank you for the feedback @DaveTCode You're completely right. We should do better in terms of errors propagation. We do have some improvements in the latest release [v0.2.2][1], but I'm going to check if it helps in such case as you described, e.g.:

```
$ k starboard kube-bench -v 3 --delete-scan-job=false --scan-job-timeout=60s
```

Sometimes it might be the underlying scanner, which does not report the error code or error message, which I'm going to double check as well.

[1]: https://github.com/aquasecurity/starboard/releases

**Comment by peddyspg** [comment]
I ran in the same issue.
But i think "startboard init" should set proper Security-, Request and Limit-Policies

**Comment by danielpacak** [comment]
> I ran in the same issue.
> But i think "startboard init" should set proper Security-, Request and Limit-Policies

Thank you @peddyspg  for the comment and sorry for reply but it got lost in this thread. Let's track this kind of additional requirements as a new discussion or request for enhancement. This issue is all about propagating errors from Kubernetes job to the Scanner CLI's output, which can be improved.

Please make sure to specify more more details when filing an issue. Explain how would you like Starboard to handle particular use case and why you think it's important.
