### ISSUE TITLE
Starboard operator crashes with panic: runtime error: index out of range [1] with length 1

### ISSUE THREAD

**Issue by Harisanthosh** [aquasecurity/starboard#751]
**What steps did you take and what happened:**
Hi, I ran across this wonderful project recently and wanted to onboard it for one of my projects. I have tried installing Starboard operator with both Helm and Kubectl with custom CRDs. The scanning works for few seconds and then my kubernetes cluster controller crashes with panic runtime error and end up in CrashLoopBackOff state. 

![image](https://user-images.githubusercontent.com/21079172/137512385-26ff4f25-832e-41c1-9dd3-3d3a4e6b5256.png)

I also tried reducing the scope of the targeted namespaces and made the operator to run in SingleNamespace mode but of no avail. Also attaching the Debug log for reference purposes. 

Debug_Log_starboard:
[starboard-operator-54644fb8bf-9qkqm.log](https://github.com/aquasecurity/starboard/files/7354314/starboard-operator-54644fb8bf-9qkqm.log)

HELM Setup: 

```
helm install starboard-operator aqua/starboard-operator -n starboard-operator \
  --set="targetNamespaces=apps" \
  --set="trivy.ignoreUnfixed=true" \
  --set="envSecret.stringData.OPERATOR_LOG_DEV_MODE=true" \
  --set="envSecret.stringData.OPERATOR_CONFIG_AUDIT_SCANNER_ENABLED=false" \
  --set="envSecret.stringData.OPERATOR_CIS_KUBERNETES_BENCHMARK_ENABLED=false"
```

Kubectl Setup steps and files:

`kubectl apply -f https://raw.githubusercontent.com/aquasecurity/starboard/v0.12.0/deploy/crd/vulnerabilityreports.crd.yaml \
  -f https://raw.githubusercontent.com/aquasecurity/starboard/v0.12.0/deploy/crd/configauditreports.crd.yaml \
  -f https://raw.githubusercontent.com/aquasecurity/starboard/v0.12.0/deploy/crd/clusterconfigauditreports.crd.yaml \
  -f https://raw.githubusercontent.com/aquasecurity/starboard/v0.12.0/deploy/crd/ciskubebenchreports.crd.yaml
`
[star-deployment.yaml.txt](https://github.com/aquasecurity/starboard/files/7354323/star-deployment.yaml.txt)
[star-configmap.yml.txt](https://github.com/aquasecurity/starboard/files/7354326/star-configmap.yml.txt)
[star-clusterrole.yml.txt](https://github.com/aquasecurity/starboard/files/7354342/star-clusterrole.yml.txt)
[star-rolebinding.yml.txt](https://github.com/aquasecurity/starboard/files/7354381/star-rolebinding.yml.txt)
[star-serviceaccount.yml.txt](https://github.com/aquasecurity/starboard/files/7354387/star-serviceaccount.yml.txt)

**What did you expect to happen:**
Expect the starboard operator to run without crashing. I have also updated the operators with multiple replicas to distribute the workloads however all the replicas are crashing with the same panic error.

I understand that it is not a direct issue pertaining to Starboard as it pertains to kubernetes controller crashing, however I wanted to bring it to notice to gain valuable inputs from the Aquasec community. 

Thanks in advance

**Environment:**

- Starboard version (use `starboard version`): 0.12.0
- Kubernetes version (use `kubectl version`): 1.19.13 running in Azure Kubernetes Service
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): Windows 10

**Comment by danielpacak** [comment]
Notice that running the Starboard Operator (or any K8s operator) with multiple replicase requires additional consideration. In particular enabling leader election so there's only one active replica in your cluster.

We should document this one better,  but to get started see the description of the `OPERATOR_LEADER_ELECTION_ENABLED` variable in the [Operator Configuration](https://aquasecurity.github.io/starboard/v0.12.0/operator/configuration/) documentation.
