### ISSUE TITLE
Starboard cli embedded into in pod, very slow when executed

### ISSUE THREAD

**Issue by vincent-pli** [aquasecurity/starboard#793]
**What steps did you take and what happened:**
I embed `starboard` cli to my image and will run it in `pod`, everything could work but I found it's very slow, cost about several minutes, that's abnormal:
```
~ $ starboard -n dev-sec get report Deployment/mq-spring-app > /report/mq-spring-app.Deployment.html
I1102 08:18:43.206004     234 request.go:665] Waited for 1.126470594s due to client-side throttling, not priority and fairness, request: GET:https://172.30.0.1:443/apis/certmanager.k8s.io/v1alpha1?timeout=32s
I1102 08:18:53.212403     234 request.go:665] Waited for 1.597164284s due to client-side throttling, not priority and fairness, request: GET:https://172.30.0.1:443/apis/tuned.openshift.io/v1?timeout=32s
I1102 08:19:03.212419     234 request.go:665] Waited for 11.596516789s due to client-side throttling, not priority and fairness, request: GET:https://172.30.0.1:443/apis/pipelines.openshift.io/v1alpha1?timeout=32s
I1102 08:19:13.411731     234 request.go:665] Waited for 21.789961168s due to client-side throttling, not priority and fairness, request: GET:https://172.30.0.1:443/apis/security.internal.openshift.io/v1?timeout=32s
I1102 08:19:23.611748     234 request.go:665] Waited for 7.395897431s due to client-side throttling, not priority and fairness, request: GET:https://172.30.0.1:443/apis/tekton.dev/v1alpha1?timeout=32s
I1102 08:19:33.612308     234 request.go:665] Waited for 17.396277128s due to client-side throttling, not priority and fairness, request: GET:https://172.30.0.1:443/apis/packages.operators.coreos.com/v1?timeout=32s
```

Seems, it's try many url one by one, could I fix it, thanks

[A clear and concise description of what the bug is, and what commands you ran.]

**What did you expect to happen:**

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Starboard version (use `starboard version`):
- Kubernetes version (use `kubectl version`):
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc):

**Comment by vincent-pli** [comment]
@danielpacak

**Comment by danielpacak** [comment]
Please provide Starboard version info and give us an idea of how many security reports (CRD instances) you're trying to export to HTML? Client-side throttling is part of client-go / K8s API Server, not Starboard.

**Comment by danielpacak** [comment]
We cannot troubleshoot without more details why Kubernetes API Server / client-go is throttling requests. Especially for requests that are not managed by Starboard.
