### ISSUE TITLE
Submit starboard CLI to krew-index

### ISSUE THREAD

**Issue by danielpacak** [aquasecurity/starboard#8]
Submit the `starboard` cli executables to [krew-index](https://github.com/kubernetes-sigs/krew-index) so we can install it with [krew](https://krew.sigs.k8s.io/):

```
$ kubectl krew install starboard
$ kubectl starboard -h
...
```

**Comment by krol3** [comment]
I'm glad to help with this item

**Comment by krol3** [comment]
Submitted  to krew-index https://github.com/kubernetes-sigs/krew-index/pull/647

**Comment by danielpacak** [comment]
Great! I think the last step to close this one is to update README https://github.com/aquasecurity/starboard#kubectl-plugin
