### ISSUE TITLE
Error scanning images from private registries using imagePullSecrets

### ISSUE THREAD

**Issue by avgkoster** [aquasecurity/starboard#835]
What steps did you take and what happened:

I have a specific namespace, for example neuvector, it has imagepullSecret: regsecret, which contains credentials from the private registry.
Starboard cannot scan it and gives an error about an empty namespace
Please tell me what I'm doing wrong?
2021-11-30T06:55:52.109Z ERROR controller.replicaset Reconciler error {"reconciler group": "apps", "reconciler kind": "ReplicaSet", "name": "neuvector-controller-pod-87dc9bbdc", "namespace": "neuvector", "error": "creating secret: an empty namespace may not be set during creation"}

Starboard 0.13.0
Kubernetes version 1.19
OS RHEL 7

**Comment by danielpacak** [comment]
:wave: @avgkoster I can reproduce this error in my environment. It's a regression. We'll try to fix it and release in v0.13.1 . Thank you for reporting and really sorry for inconvenience

**Comment by danielpacak** [comment]
@avgkoster The fix has been released in https://github.com/aquasecurity/starboard/releases/tag/v0.13.1
