### ISSUE TITLE
Ignore parsing logs of scan jobs have been deleted

### ISSUE THREAD

**Issue by danielpacak** [aquasecurity/starboard#873]
In the configauditreports controller we should ignore scan jobs that are cached but had been deleted from etcd so we cannot parse their logs. Currently we return an error, which is causing retry, but retrying does not make much sense in this case.

https://github.com/aquasecurity/starboard/blob/v0.13.0/pkg/operator/controller/configauditreport.go#L406

**Comment by py-go** [comment]
@danielpacak - Can we try to handle this with the check of [IsNotFound](https://pkg.go.dev/k8s.io/apimachinery/pkg/api/errors#IsNotFound) like this:
```
logsStream, err := r.LogsReader.GetLogsByJobAndContainerName(ctx, job, r.Plugin.GetContainerName())
if err != nil {
    // Check if the error is related to not found
    if errors.IsNotFound(err){
        log.V(1).Info("Deleting complete scan job", "owner", owner)
        return r.deleteJob(ctx, job)
    }
    return fmt.Errorf("getting logs: %w", err)
}

```

```

func (r *logsReader) GetLogsByJobAndContainerName(ctx context.Context, job *batchv1.Job, containerName string) (io.ReadCloser, error) {
	pod, err := r.getPodByJob(ctx, job)
       // Return actual error
	if err != nil {
		return nil, err
	}
	...
}
```
