### ISSUE TITLE
 starboard find vulns deployment/some_deployment stuck

### ISSUE THREAD

**Issue by rogeduardo** [aquasecurity/starboard#88]
```
# starboard find vulnerabilities deployment/nginx -v 3
I0710 18:23:06.513704    9492 scanner.go:56] Getting Pod template for workload: {Deployment nginx default}
I0710 18:23:06.543574    9492 scanner.go:71] Scanning with options: {ScanJobTimeout:0s DeleteScanJob:true}
I0710 18:23:06.543714    9492 runner.go:79] Running task and waiting forever
I0710 18:23:06.543783    9492 runnable_job.go:47] Creating runnable job: starboard/d0b993ac-4713-4c1b-b4e2-d139d867b99f
I0710 18:23:06.559944    9492 reflector.go:207] Starting reflector *v1.Job (30m0s) from pkg/mod/k8s.io/client-go@v0.19.0-alpha.3/tools/cache/reflector.go:156
I0710 18:23:06.559976    9492 reflector.go:243] Listing and watching *v1.Job from pkg/mod/k8s.io/client-go@v0.19.0-alpha.3/tools/cache/reflector.go:156
```
I did the Getting Started section from starboard git page and I stucked on this step, because this command never end. Where I could see what is wrong about it?

I'm using Kind (https://github.com/kubernetes-sigs/kind) to make the Kubernetes cluster.

**Environment:**
- Starboard Version: {Version:0.2.6 Commit:d43faefc56021ae55d4574054ce7de13175ca206 Date:2020-07-09T20:30:45Z}
- Kubernetes version:
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:47:41Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-30T20:19:45Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
- OS: CentOS Linux release 7.7.1908 (Core)

**Comment by Krishan-Sharma** [comment]
Thanks for reporting the issue @rogeduardo. I tried to reproduce the same with v0.2.6 version of starboard against an EKS cluster and I was not able to reproduce the issue.

There are two things that jump out from the logs. One is that we are creating a task and waiting forever:
_I0710 18:23:06.543714    9492 runner.go:79] Running task and waiting forever_

And, the second is that the difference in your and my setup seems to be of the underlying platform (kind for you and EKS for me). To see what else is happening, can you execute the below commands and provide the output?


- kubectl describe job (the-one-that-is-shown-in-logs) -n starboard
- kubectl logs (corresponding-pod-if-any) -n starboard

**Comment by rogeduardo** [comment]
I discover my problem and isn't with starboard, it is with my network. Thank you for the help.
