### ISSUE TITLE
docs: write troubleshooting checklist for Starboard Operator

### ISSUE THREAD

**Issue by danielpacak** [aquasecurity/starboard#884]
There's always the same procedure to figure out why Starboard Operator is failing. Usually it allows us to narrow down the root cause to a bug in code or configuration / platform issue. We should have this documented.

**Comment by AnaisUrlichs** [comment]
What are some of the common troubleshooting issues or should I just give it a go? @danielpacak

**Comment by danielpacak** [comment]
Just give it a go! Troubleshooting would start like with any other Pod or Deployment. We can take it from there and add Starboard-specific checklist.
