### ISSUE TITLE
starboard uses deprecated trivy cmd invocation

### ISSUE THREAD

**Issue by Arabus** [aquasecurity/starboard#888]
**What steps did you take and what happened:**

Deploy starboard operator via helm with value `trivy.imageRef: docker.io/aquasec/trivy:0.22.0`
Run `kubectl log scan-vulnerabilityreport-7bdd6fbffb-47ks9`
Get `2022-01-06T09:22:57.547Z        WARN    The root command will be removed. Please migrate to 'trivy image' command. See https://github.com/aquasecurity/trivy/discussions/1515`
 
**What did you expect to happen:**

No Warning

**Anything else you would like to add:**

If I understand correctly, the code at 
https://github.com/aquasecurity/starboard/blob/8f637cfd5c9dd64f56a2ab8e0ee81cc85c174b7c/pkg/plugin/trivy/plugin.go#L535
needs to be changed to use the new cli format for trivy e.g.,
```
			Args: []string{
				"--cache-dir",
				"/var/lib/trivy",
				"--quiet",
                                 "image",
				"--skip-update",
				"--format",
				"json",
				optionalMirroredImage,
			},
```

If you like I can provide an appropriate merge request.

**Environment:**

- Starboard version (use `starboard version`): Operator 0.13.2
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:33:37Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T20:59:07Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc):
```
ProductName:    macOS
ProductVersion: 11.6.2
BuildVersion:   20G314
```

**Comment by danielpacak** [comment]
Good catch @Arabus Certainly we'd want to use the `trivy image` subcommand in this case and get rid of any warnings.

If you could work on that that would be awesome. Note that we are working on Trivy filesystem "mode" in scope of #872 so make sure that you only change what's absolutely necessary for your merge request.
