### ISSUE TITLE
[operator] strange log message gzip: invalid

### ISSUE THREAD

**Issue by NissesSenap** [aquasecurity/starboard#903]
**What steps did you take and what happened:**

Getting the following error:

```
{"level":"error","ts":1642143772.741397,"logger":"reconciler.vulnerabilityreport","msg":"Scan job container","job":"starboard-operator/scan-vulnerabilityreport-d84c5c4dc","container":"liveness-probe","status.reason":"Error","status.message":"2022-01-14T07:02:52.076Z\t\u001b[31mFATAL\u001b[0m\terror in image scan: failed analysis: analyze error: failed to analyze layer: sha256:ad6d58c8e6c2d61b3d641d98eaea8f66d25626f3a2f9ba90e8eadff03ca56155 : unable to get uncompressed layer sha256:ad6d58c8e6c2d61b3d641d98eaea8f66d25626f3a2f9ba90e8eadff03ca56155: failed to get the layer content (sha256:ad6d58c8e6c2d61b3d641d98eaea8f66d25626f3a2f9ba90e8eadff03ca56155): gzip: invalid header\n","stacktrace":"sigs.k8s.io/controller-runtime/pkg/reconcile.Func.Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.3/pkg/reconcile/reconcile.go:102\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.3/pkg/internal/controller/controller.go:114\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.3/pkg/internal/controller/controller.go:311\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.3/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.3/pkg/internal/controller/controller.go:227"}
```

Running starboard operator with the following config on helm release `0.8.2`

```values.yaml
targetNamespaces: ""

trivy:
  mode: ClientServer
  severity: MEDIUM,HIGH,CRITICAL
  ignoreUnfixed: true
  serverURL: "http://trivy.trivy.svc.cluster.local:4954"

operator:
  configAuditScannerEnabled: false
  kubernetesBenchmarkEnabled: false
```

Running trivy helm release `0.4.9` with it's default settings.

**What did you expect to happen:**
Not to get this error. Don't know why I get it. I think it's because trivy can't download the image but I'm unsure.

**Anything else you would like to add:**
I can see that the vulnerabilityreports gets generated and it contain CVE information. I haven't been able to verify if i get the CVE information if I get the error.

In this example it's one of the following images and they are public and ready to download.

```
      image: mcr.azk8s.cn/oss/kubernetes-csi/csi-node-driver-registrar:v2.3.0
      image: mcr.microsoft.com/oss/kubernetes-csi/csi-node-driver-registrar:v2.3.0
```

I get this for a number of other containers as well and all of them are located on public repos.

[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Starboard version (use `starboard version`): 0.13.2
- tryvy version: 0.22.0

**Comment by danielpacak** [comment]
Are you sure mcr.azk8s.cn is public? I'm getting 403. I can pull from mcr.microsoft.com without credentials though.
```
$ docker pull mcr.azk8s.cn/oss/kubernetes-csi/csi-node-driver-registrar:v2.3.0
Error response from daemon: error parsing HTTP 403 response body: invalid character '<' looking for beginning of value: "<html>\r\n<head><title>403 Forbidden</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>403 Forbidden</h1></center>\r\n<hr><center>nginx/1.14.0 (Ubuntu)</center>\r\n</body>\r\n</html>\r\n"
```

**Comment by chen-keinan** [comment]
Hi @NissesSenap,
by looking at the error, `failed to get the layer content --> gzip: invalid header`,  I suspect that Trivy is if failing to inspect the layer due to following reasons:
1. Layer is not compressed with `gz`, a.k.a. `tar.bzip` (In this case, Trivy cannot scan the layer.)
2. Network issue, In this case, can you try to reproduce it again ?

**Comment by NissesSenap** [comment]
> Are you sure mcr.azk8s.cn is public? I'm getting 403. I can pull from mcr.microsoft.com without credentials though.
> 
> ```
> $ docker pull mcr.azk8s.cn/oss/kubernetes-csi/csi-node-driver-registrar:v2.3.0
> Error response from daemon: error parsing HTTP 403 response body: invalid character '<' looking for beginning of value: "<html>\r\n<head><title>403 Forbidden</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>403 Forbidden</h1></center>\r\n<hr><center>nginx/1.14.0 (Ubuntu)</center>\r\n</body>\r\n</html>\r\n"
> ```

My bad @danielpacak I honestly just assumed that it was public so didn't try for some reason. Why in the world would this very open-source project not be hosted in a public repo? I assume that it's some internal azure image that I can reach since I'm running AKS but it's very strange why azure would store behind a login.

@chen-keinan  I haven't looked at this part of the code but would it be hard to actually show a 403 error to make it super clear that me as a user actually don't have access to download it? I guess it depends on how trivy responds to these kind of errors.

I will try to play around with this a bit more during the week but sadly I don't have super much time right now.

**Comment by chen-keinan** [comment]
@NissesSenap for the 403 error Trivy will return a different error :
 `2022-01-17T10:30:42.106+0200	FATAL	scan error: unable to initialize a scanner: unable to initialize a docker scanner: 3 errors occurred:
	* unable to inspect the image (mcr.azk8s.cn/oss/kubernetes-csi/csi-node-driver-registrar:v2.3.0): Error: No such image: mcr.azk8s.cn/oss/kubernetes-csi/csi-node-driver-registrar:v2.3.0
	* unable to initialize Podman client: no podman socket found: stat podman/podman.sock: no such file or directory
	* GET https://mcr.azk8s.cn/v2/: unexpected status code 403 Forbidden: <html>
<head><title>403 Forbidden</title></head>
<body bgcolor="white">
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx/1.14.0 (Ubuntu)</center>
</body>
</html>`
I assume that  for the `gzip: invalid header` error, it is  related to layer compression not supported

**Comment by NissesSenap** [comment]
Fair enough. Thanks for the quick response from both of you.
I will close the issue :)
