### ISSUE TITLE
client_integration_test.go isn't under itest dir

### ISSUE THREAD

**Issue by 06kellyjac** [aquasecurity/starboard#914]
**What steps did you take and what happened:**

`client_integration_test.go` is an integration test but not under the `itest` directory

this means if I filter out itests I'll still hit `client_integration_test.go` which fails in my sandbox that has no networking

**What did you expect to happen:**

Is it possible to move it under the `itest` directory? if not I'm fine just `rm`ing the file before I run the tests

**Comment by danielpacak** [comment]
From what I can see there is no such file `client_integration_test.go` in this repository.

**Comment by 06kellyjac** [comment]
https://github.com/aquasecurity/starboard/blob/main/pkg/plugin/aqua/client/client_integration_test.go

**Comment by 06kellyjac** [comment]
ctrl + t is nice for searching for files in GH

**Comment by danielpacak** [comment]
My bad, I used find in files feature instead of looking for file names.

This particular test is skipped if you run it with `go run -short`. (See the full command in make unit-tests definition.) What's more, we are going to deprecate plugin for Aqua Enterprise scanner.

**Comment by 06kellyjac** [comment]
:+1: cool thanks
