### ISSUE TITLE
scanJobTimeout is not fully respected

### ISSUE THREAD

**Issue by bgoareguer** [aquasecurity/starboard#942]
Using the starboard operator the `scanJobTimeout` parameter has a default value of `5m`.

When using a slow internet connection, I tried to increase the `scanJobTimeout` to `10m` so that Trivy can download the image before the timeout is reached.

But the scan job terminates before the 10m timeout.

In fact the `scanJobTimeout` is only used to define the `activeDeadlineSeconds` of the scan job, it does not configure the Trivy timeout (which is also set to `5m` by default, see [here](https://github.com/aquasecurity/trivy/blob/cabd18daae14ed3ac6177eeafdc0c53e5763a700/pkg/commands/app.go#L197-L202)) 

The corresponding chunks of code in starboard are located [here](https://github.com/aquasecurity/starboard/blob/main/pkg/plugin/trivy/plugin.go#L393-L398) and [here](https://github.com/aquasecurity/starboard/blob/b2a8c0d3b5233c98471cec51c16fb845a7dddd60/pkg/plugin/trivy/plugin.go#L559-L567)).

**Comment by chen-keinan** [comment]
@bgoareguer, thank you for this input, exposing `TRIVY_TIMEOUT` probably will solve this issue
