### ISSUE TITLE
No container image built or binary released for arm => Helm Chart and other examples do not work on Apple M1

### ISSUE THREAD

**Issue by AnaisUrlichs** [aquasecurity/starboard#976]
**What steps did you take and what happened:**

I installed the Helm Chart from the aqua repo like detailed in the docs. However, the pods is crashlooping 
![Screenshot 2022-02-21 at 09 24 06](https://user-images.githubusercontent.com/33576047/154926680-492a72a9-a5ff-4af2-9260-cdd8d5448b0d.png)

![Screenshot 2022-02-21 at 09 23 26](https://user-images.githubusercontent.com/33576047/154926684-ea7ac9aa-5efc-4498-b461-fc00f23ba351.png)

[A clear and concise description of what the bug is, and what commands you ran.]

```
helm repo add aqua https://aquasecurity.github.io/helm-charts/

helm repo update

helm install starboard-operator aqua/starboard-operator \
  --namespace starboard-system \
  --create-namespace \
  --set="targetNamespaces=default" \
  --set="trivy.ignoreUnfixed=true" \
  --version 0.9.1
```

I ran this on microk8s with dns enabled on my mbp silicon 

**What did you expect to happen:**

Lots of developers want to try out Starboard on their local machine and if they run on the new Apple silicon they are unable to do so, and might think Starboard does not work rather it being environment specific. 

To improve the developer experience, we need to ensure that users can run example on their local machine. 
When I install the Helm Chart, I want it to use automatically the image applicable to me.

**Anything else you would like to add:**

We are currently not building arm images (or we are building them but not pushing them to Dockerhub)
https://hub.docker.com/r/aquasec/starboard/tags

I am not sure how this works, maybe we build them but do not push or release those images?
https://github.com/aquasecurity/starboard/blob/d656c59e003b2156f0efb0a1e2e9160712720493/.goreleaser.yaml#L219

Resulting, also these examples using Docker and the binary does not work on the new macs 
https://aquasecurity.github.io/starboard/v0.14.1/cli/installation/docker/
https://github.com/aquasecurity/starboard/releases

[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Starboard version (use `starboard version`): Helm Chart 9.1 Starboard version 0.14.1
- Kubernetes version (use `kubectl version`): 
![Screenshot 2022-02-21 at 09 46 36](https://user-images.githubusercontent.com/33576047/154929763-d26aa0e9-1d34-4483-bb9c-8552bad78be9.png)

- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): macOS 12.2.1

**Comment by danielpacak** [comment]
This issue is a duplicate of #831 , which has been resolved in #955 . It hasn't been released yet, but it's in scope of the [v0.15.0](https://github.com/aquasecurity/starboard/milestone/21) milestone.
