### ISSUE TITLE
The cleanup command should wait for the starboard namespace termination

### ISSUE THREAD

**Issue by danielpacak** [aquasecurity/starboard#99]
**Describe the problem/challenge you have**

The starboard cleanup command sends a request to Kubernetes API, but does not wait for the starboard namespace termination.

For example, running `$ starboard init` immediately after `$ starboard cleanup` might fail. 

**Describe the solution you'd like**

The command should exit only if the underlying namespace is terminated

**Environment:**

- Starboard version (use `starboard version`): 0.2.6
- Kubernetes version (use `kubectl version`): Any
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): Any

**Comment by krol3** [comment]
I'd could help with this item
